// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: gravity_metrics.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Enhanced ServerMetrics with comprehensive performance and health data
type ServerMetrics struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Basic server metrics (1-10)
	StartTime       int64  `protobuf:"varint,1,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`                     // epoch milliseconds
	Uptime          uint64 `protobuf:"varint,2,opt,name=uptime,proto3" json:"uptime,omitempty"`                                            // milliseconds since start
	ConnectedTime   int64  `protobuf:"varint,3,opt,name=connected_time,json=connectedTime,proto3" json:"connected_time,omitempty"`         // epoch milliseconds (optional)
	LastMessageTime int64  `protobuf:"varint,4,opt,name=last_message_time,json=lastMessageTime,proto3" json:"last_message_time,omitempty"` // epoch milliseconds (optional)
	// Connection metrics (11-20)
	IsConnected      bool  `protobuf:"varint,11,opt,name=is_connected,json=isConnected,proto3" json:"is_connected,omitempty"`
	ReconnectCount   int64 `protobuf:"varint,12,opt,name=reconnect_count,json=reconnectCount,proto3" json:"reconnect_count,omitempty"`
	TotalConnections int64 `protobuf:"varint,13,opt,name=total_connections,json=totalConnections,proto3" json:"total_connections,omitempty"`
	// Component metrics (21-40)
	GrpcMetrics   *GRPCConnectionMetrics `protobuf:"bytes,21,opt,name=grpc_metrics,json=grpcMetrics,proto3" json:"grpc_metrics,omitempty"`
	Performance   *PerformanceMetrics    `protobuf:"bytes,22,opt,name=performance,proto3" json:"performance,omitempty"`
	MessageStats  *MessageStatistics     `protobuf:"bytes,23,opt,name=message_stats,json=messageStats,proto3" json:"message_stats,omitempty"`
	SystemMetrics *SystemResourceMetrics `protobuf:"bytes,24,opt,name=system_metrics,json=systemMetrics,proto3" json:"system_metrics,omitempty"`
	// Historical data (41-50)
	HistoricalData *HistoricalMetrics `protobuf:"bytes,41,opt,name=historical_data,json=historicalData,proto3" json:"historical_data,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ServerMetrics) Reset() {
	*x = ServerMetrics{}
	mi := &file_gravity_metrics_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerMetrics) ProtoMessage() {}

func (x *ServerMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_gravity_metrics_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerMetrics.ProtoReflect.Descriptor instead.
func (*ServerMetrics) Descriptor() ([]byte, []int) {
	return file_gravity_metrics_proto_rawDescGZIP(), []int{0}
}

func (x *ServerMetrics) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *ServerMetrics) GetUptime() uint64 {
	if x != nil {
		return x.Uptime
	}
	return 0
}

func (x *ServerMetrics) GetConnectedTime() int64 {
	if x != nil {
		return x.ConnectedTime
	}
	return 0
}

func (x *ServerMetrics) GetLastMessageTime() int64 {
	if x != nil {
		return x.LastMessageTime
	}
	return 0
}

func (x *ServerMetrics) GetIsConnected() bool {
	if x != nil {
		return x.IsConnected
	}
	return false
}

func (x *ServerMetrics) GetReconnectCount() int64 {
	if x != nil {
		return x.ReconnectCount
	}
	return 0
}

func (x *ServerMetrics) GetTotalConnections() int64 {
	if x != nil {
		return x.TotalConnections
	}
	return 0
}

func (x *ServerMetrics) GetGrpcMetrics() *GRPCConnectionMetrics {
	if x != nil {
		return x.GrpcMetrics
	}
	return nil
}

func (x *ServerMetrics) GetPerformance() *PerformanceMetrics {
	if x != nil {
		return x.Performance
	}
	return nil
}

func (x *ServerMetrics) GetMessageStats() *MessageStatistics {
	if x != nil {
		return x.MessageStats
	}
	return nil
}

func (x *ServerMetrics) GetSystemMetrics() *SystemResourceMetrics {
	if x != nil {
		return x.SystemMetrics
	}
	return nil
}

func (x *ServerMetrics) GetHistoricalData() *HistoricalMetrics {
	if x != nil {
		return x.HistoricalData
	}
	return nil
}

// GRPCConnectionMetrics contains gRPC-specific connection metrics
type GRPCConnectionMetrics struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Connection pool information (1-10)
	PoolSize          int32    `protobuf:"varint,1,opt,name=pool_size,json=poolSize,proto3" json:"pool_size,omitempty"`
	ActiveConnections int32    `protobuf:"varint,2,opt,name=active_connections,json=activeConnections,proto3" json:"active_connections,omitempty"`
	IdleConnections   int32    `protobuf:"varint,3,opt,name=idle_connections,json=idleConnections,proto3" json:"idle_connections,omitempty"`
	FailedConnections int32    `protobuf:"varint,4,opt,name=failed_connections,json=failedConnections,proto3" json:"failed_connections,omitempty"`
	ConnectionStates  []string `protobuf:"bytes,5,rep,name=connection_states,json=connectionStates,proto3" json:"connection_states,omitempty"`
	// Stream information (11-20)
	TotalStreams     int32  `protobuf:"varint,11,opt,name=total_streams,json=totalStreams,proto3" json:"total_streams,omitempty"`
	ControlStreams   int32  `protobuf:"varint,12,opt,name=control_streams,json=controlStreams,proto3" json:"control_streams,omitempty"`
	TunnelStreams    int32  `protobuf:"varint,13,opt,name=tunnel_streams,json=tunnelStreams,proto3" json:"tunnel_streams,omitempty"`
	HealthyStreams   int32  `protobuf:"varint,14,opt,name=healthy_streams,json=healthyStreams,proto3" json:"healthy_streams,omitempty"`
	ActiveStreams    int32  `protobuf:"varint,15,opt,name=active_streams,json=activeStreams,proto3" json:"active_streams,omitempty"`
	StreamAllocation string `protobuf:"bytes,16,opt,name=stream_allocation,json=streamAllocation,proto3" json:"stream_allocation,omitempty"` // allocation strategy
	// Protocol information (21-30)
	ProtocolVersion    string `protobuf:"bytes,21,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	CompressionEnabled bool   `protobuf:"varint,22,opt,name=compression_enabled,json=compressionEnabled,proto3" json:"compression_enabled,omitempty"`
	TlsVersion         string `protobuf:"bytes,23,opt,name=tls_version,json=tlsVersion,proto3" json:"tls_version,omitempty"`
	// Health monitoring (31-40)
	LastHealthCheck       int64    `protobuf:"varint,31,opt,name=last_health_check,json=lastHealthCheck,proto3" json:"last_health_check,omitempty"`                     // epoch milliseconds
	HealthCheckIntervalNs int64    `protobuf:"varint,32,opt,name=health_check_interval_ns,json=healthCheckIntervalNs,proto3" json:"health_check_interval_ns,omitempty"` // nanoseconds
	UnhealthyStreams      []string `protobuf:"bytes,33,rep,name=unhealthy_streams,json=unhealthyStreams,proto3" json:"unhealthy_streams,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *GRPCConnectionMetrics) Reset() {
	*x = GRPCConnectionMetrics{}
	mi := &file_gravity_metrics_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GRPCConnectionMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GRPCConnectionMetrics) ProtoMessage() {}

func (x *GRPCConnectionMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_gravity_metrics_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GRPCConnectionMetrics.ProtoReflect.Descriptor instead.
func (*GRPCConnectionMetrics) Descriptor() ([]byte, []int) {
	return file_gravity_metrics_proto_rawDescGZIP(), []int{1}
}

func (x *GRPCConnectionMetrics) GetPoolSize() int32 {
	if x != nil {
		return x.PoolSize
	}
	return 0
}

func (x *GRPCConnectionMetrics) GetActiveConnections() int32 {
	if x != nil {
		return x.ActiveConnections
	}
	return 0
}

func (x *GRPCConnectionMetrics) GetIdleConnections() int32 {
	if x != nil {
		return x.IdleConnections
	}
	return 0
}

func (x *GRPCConnectionMetrics) GetFailedConnections() int32 {
	if x != nil {
		return x.FailedConnections
	}
	return 0
}

func (x *GRPCConnectionMetrics) GetConnectionStates() []string {
	if x != nil {
		return x.ConnectionStates
	}
	return nil
}

func (x *GRPCConnectionMetrics) GetTotalStreams() int32 {
	if x != nil {
		return x.TotalStreams
	}
	return 0
}

func (x *GRPCConnectionMetrics) GetControlStreams() int32 {
	if x != nil {
		return x.ControlStreams
	}
	return 0
}

func (x *GRPCConnectionMetrics) GetTunnelStreams() int32 {
	if x != nil {
		return x.TunnelStreams
	}
	return 0
}

func (x *GRPCConnectionMetrics) GetHealthyStreams() int32 {
	if x != nil {
		return x.HealthyStreams
	}
	return 0
}

func (x *GRPCConnectionMetrics) GetActiveStreams() int32 {
	if x != nil {
		return x.ActiveStreams
	}
	return 0
}

func (x *GRPCConnectionMetrics) GetStreamAllocation() string {
	if x != nil {
		return x.StreamAllocation
	}
	return ""
}

func (x *GRPCConnectionMetrics) GetProtocolVersion() string {
	if x != nil {
		return x.ProtocolVersion
	}
	return ""
}

func (x *GRPCConnectionMetrics) GetCompressionEnabled() bool {
	if x != nil {
		return x.CompressionEnabled
	}
	return false
}

func (x *GRPCConnectionMetrics) GetTlsVersion() string {
	if x != nil {
		return x.TlsVersion
	}
	return ""
}

func (x *GRPCConnectionMetrics) GetLastHealthCheck() int64 {
	if x != nil {
		return x.LastHealthCheck
	}
	return 0
}

func (x *GRPCConnectionMetrics) GetHealthCheckIntervalNs() int64 {
	if x != nil {
		return x.HealthCheckIntervalNs
	}
	return 0
}

func (x *GRPCConnectionMetrics) GetUnhealthyStreams() []string {
	if x != nil {
		return x.UnhealthyStreams
	}
	return nil
}

// PerformanceMetrics contains performance data from MetricsCollector
type PerformanceMetrics struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Latency metrics (1-10) - all in nanoseconds
	AvgPacketLatencyNs  int64 `protobuf:"varint,1,opt,name=avg_packet_latency_ns,json=avgPacketLatencyNs,proto3" json:"avg_packet_latency_ns,omitempty"`
	P95PacketLatencyNs  int64 `protobuf:"varint,2,opt,name=p95_packet_latency_ns,json=p95PacketLatencyNs,proto3" json:"p95_packet_latency_ns,omitempty"`
	P99PacketLatencyNs  int64 `protobuf:"varint,3,opt,name=p99_packet_latency_ns,json=p99PacketLatencyNs,proto3" json:"p99_packet_latency_ns,omitempty"`
	MaxPacketLatencyNs  int64 `protobuf:"varint,4,opt,name=max_packet_latency_ns,json=maxPacketLatencyNs,proto3" json:"max_packet_latency_ns,omitempty"`
	AvgControlLatencyNs int64 `protobuf:"varint,5,opt,name=avg_control_latency_ns,json=avgControlLatencyNs,proto3" json:"avg_control_latency_ns,omitempty"`
	P95ControlLatencyNs int64 `protobuf:"varint,6,opt,name=p95_control_latency_ns,json=p95ControlLatencyNs,proto3" json:"p95_control_latency_ns,omitempty"`
	// Throughput metrics (11-20)
	PacketsPerSecond      float64 `protobuf:"fixed64,11,opt,name=packets_per_second,json=packetsPerSecond,proto3" json:"packets_per_second,omitempty"`
	BytesPerSecond        float64 `protobuf:"fixed64,12,opt,name=bytes_per_second,json=bytesPerSecond,proto3" json:"bytes_per_second,omitempty"`
	ControlMessagesPerSec float64 `protobuf:"fixed64,13,opt,name=control_messages_per_sec,json=controlMessagesPerSec,proto3" json:"control_messages_per_sec,omitempty"`
	// Error metrics (21-30)
	ErrorRate        float64 `protobuf:"fixed64,21,opt,name=error_rate,json=errorRate,proto3" json:"error_rate,omitempty"` // percentage
	PacketDrops      int64   `protobuf:"varint,22,opt,name=packet_drops,json=packetDrops,proto3" json:"packet_drops,omitempty"`
	StreamErrors     int64   `protobuf:"varint,23,opt,name=stream_errors,json=streamErrors,proto3" json:"stream_errors,omitempty"`
	ConnectionErrors int64   `protobuf:"varint,24,opt,name=connection_errors,json=connectionErrors,proto3" json:"connection_errors,omitempty"`
	// Stream health (31-40)
	HealthyStreams    int64   `protobuf:"varint,31,opt,name=healthy_streams,json=healthyStreams,proto3" json:"healthy_streams,omitempty"`
	TotalStreams      int64   `protobuf:"varint,32,opt,name=total_streams,json=totalStreams,proto3" json:"total_streams,omitempty"`
	ActiveConnections int64   `protobuf:"varint,33,opt,name=active_connections,json=activeConnections,proto3" json:"active_connections,omitempty"`
	UnhealthyStreams  int64   `protobuf:"varint,34,opt,name=unhealthy_streams,json=unhealthyStreams,proto3" json:"unhealthy_streams,omitempty"`
	StreamUtilization float64 `protobuf:"fixed64,35,opt,name=stream_utilization,json=streamUtilization,proto3" json:"stream_utilization,omitempty"` // percentage
	// Circuit breaker metrics (41-50)
	CircuitBreakerStates []string `protobuf:"bytes,41,rep,name=circuit_breaker_states,json=circuitBreakerStates,proto3" json:"circuit_breaker_states,omitempty"`
	TotalCircuitBreaks   int64    `protobuf:"varint,42,opt,name=total_circuit_breaks,json=totalCircuitBreaks,proto3" json:"total_circuit_breaks,omitempty"`
	AvgRecoveryTimeNs    int64    `protobuf:"varint,43,opt,name=avg_recovery_time_ns,json=avgRecoveryTimeNs,proto3" json:"avg_recovery_time_ns,omitempty"`
	// Compression metrics (51-60)
	CompressionRatio    float64 `protobuf:"fixed64,51,opt,name=compression_ratio,json=compressionRatio,proto3" json:"compression_ratio,omitempty"` // percentage
	BytesSaved          int64   `protobuf:"varint,52,opt,name=bytes_saved,json=bytesSaved,proto3" json:"bytes_saved,omitempty"`
	CompressionTimeNs   int64   `protobuf:"varint,53,opt,name=compression_time_ns,json=compressionTimeNs,proto3" json:"compression_time_ns,omitempty"`
	DecompressionTimeNs int64   `protobuf:"varint,54,opt,name=decompression_time_ns,json=decompressionTimeNs,proto3" json:"decompression_time_ns,omitempty"`
	// Retry metrics (61-70)
	TotalRetryAttempts int64   `protobuf:"varint,61,opt,name=total_retry_attempts,json=totalRetryAttempts,proto3" json:"total_retry_attempts,omitempty"`
	SuccessfulRetries  int64   `protobuf:"varint,62,opt,name=successful_retries,json=successfulRetries,proto3" json:"successful_retries,omitempty"`
	FailedRetries      int64   `protobuf:"varint,63,opt,name=failed_retries,json=failedRetries,proto3" json:"failed_retries,omitempty"`
	RetrySuccessRate   float64 `protobuf:"fixed64,64,opt,name=retry_success_rate,json=retrySuccessRate,proto3" json:"retry_success_rate,omitempty"` // percentage
	// Connection pool metrics (71-80)
	PoolUtilization  float64 `protobuf:"fixed64,71,opt,name=pool_utilization,json=poolUtilization,proto3" json:"pool_utilization,omitempty"` // percentage
	IdleConnections  int64   `protobuf:"varint,72,opt,name=idle_connections,json=idleConnections,proto3" json:"idle_connections,omitempty"`
	ConnectionResets int64   `protobuf:"varint,73,opt,name=connection_resets,json=connectionResets,proto3" json:"connection_resets,omitempty"`
	// Resource utilization (81-90)
	MemoryUsageBytes int64 `protobuf:"varint,81,opt,name=memory_usage_bytes,json=memoryUsageBytes,proto3" json:"memory_usage_bytes,omitempty"`
	BufferPoolSize   int64 `protobuf:"varint,82,opt,name=buffer_pool_size,json=bufferPoolSize,proto3" json:"buffer_pool_size,omitempty"`
	BufferPoolHits   int64 `protobuf:"varint,83,opt,name=buffer_pool_hits,json=bufferPoolHits,proto3" json:"buffer_pool_hits,omitempty"`
	BufferPoolMisses int64 `protobuf:"varint,84,opt,name=buffer_pool_misses,json=bufferPoolMisses,proto3" json:"buffer_pool_misses,omitempty"`
	// Metadata and timing (91-100)
	LastUpdated          int64 `protobuf:"varint,91,opt,name=last_updated,json=lastUpdated,proto3" json:"last_updated,omitempty"`                              // epoch milliseconds
	CollectionIntervalNs int64 `protobuf:"varint,92,opt,name=collection_interval_ns,json=collectionIntervalNs,proto3" json:"collection_interval_ns,omitempty"` // nanoseconds
	// Runtime metrics (101-110)
	RuntimeStats  map[string]*ProjectRuntimeStats `protobuf:"bytes,101,rep,name=runtime_stats,json=runtimeStats,proto3" json:"runtime_stats,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PerformanceMetrics) Reset() {
	*x = PerformanceMetrics{}
	mi := &file_gravity_metrics_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PerformanceMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PerformanceMetrics) ProtoMessage() {}

func (x *PerformanceMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_gravity_metrics_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PerformanceMetrics.ProtoReflect.Descriptor instead.
func (*PerformanceMetrics) Descriptor() ([]byte, []int) {
	return file_gravity_metrics_proto_rawDescGZIP(), []int{2}
}

func (x *PerformanceMetrics) GetAvgPacketLatencyNs() int64 {
	if x != nil {
		return x.AvgPacketLatencyNs
	}
	return 0
}

func (x *PerformanceMetrics) GetP95PacketLatencyNs() int64 {
	if x != nil {
		return x.P95PacketLatencyNs
	}
	return 0
}

func (x *PerformanceMetrics) GetP99PacketLatencyNs() int64 {
	if x != nil {
		return x.P99PacketLatencyNs
	}
	return 0
}

func (x *PerformanceMetrics) GetMaxPacketLatencyNs() int64 {
	if x != nil {
		return x.MaxPacketLatencyNs
	}
	return 0
}

func (x *PerformanceMetrics) GetAvgControlLatencyNs() int64 {
	if x != nil {
		return x.AvgControlLatencyNs
	}
	return 0
}

func (x *PerformanceMetrics) GetP95ControlLatencyNs() int64 {
	if x != nil {
		return x.P95ControlLatencyNs
	}
	return 0
}

func (x *PerformanceMetrics) GetPacketsPerSecond() float64 {
	if x != nil {
		return x.PacketsPerSecond
	}
	return 0
}

func (x *PerformanceMetrics) GetBytesPerSecond() float64 {
	if x != nil {
		return x.BytesPerSecond
	}
	return 0
}

func (x *PerformanceMetrics) GetControlMessagesPerSec() float64 {
	if x != nil {
		return x.ControlMessagesPerSec
	}
	return 0
}

func (x *PerformanceMetrics) GetErrorRate() float64 {
	if x != nil {
		return x.ErrorRate
	}
	return 0
}

func (x *PerformanceMetrics) GetPacketDrops() int64 {
	if x != nil {
		return x.PacketDrops
	}
	return 0
}

func (x *PerformanceMetrics) GetStreamErrors() int64 {
	if x != nil {
		return x.StreamErrors
	}
	return 0
}

func (x *PerformanceMetrics) GetConnectionErrors() int64 {
	if x != nil {
		return x.ConnectionErrors
	}
	return 0
}

func (x *PerformanceMetrics) GetHealthyStreams() int64 {
	if x != nil {
		return x.HealthyStreams
	}
	return 0
}

func (x *PerformanceMetrics) GetTotalStreams() int64 {
	if x != nil {
		return x.TotalStreams
	}
	return 0
}

func (x *PerformanceMetrics) GetActiveConnections() int64 {
	if x != nil {
		return x.ActiveConnections
	}
	return 0
}

func (x *PerformanceMetrics) GetUnhealthyStreams() int64 {
	if x != nil {
		return x.UnhealthyStreams
	}
	return 0
}

func (x *PerformanceMetrics) GetStreamUtilization() float64 {
	if x != nil {
		return x.StreamUtilization
	}
	return 0
}

func (x *PerformanceMetrics) GetCircuitBreakerStates() []string {
	if x != nil {
		return x.CircuitBreakerStates
	}
	return nil
}

func (x *PerformanceMetrics) GetTotalCircuitBreaks() int64 {
	if x != nil {
		return x.TotalCircuitBreaks
	}
	return 0
}

func (x *PerformanceMetrics) GetAvgRecoveryTimeNs() int64 {
	if x != nil {
		return x.AvgRecoveryTimeNs
	}
	return 0
}

func (x *PerformanceMetrics) GetCompressionRatio() float64 {
	if x != nil {
		return x.CompressionRatio
	}
	return 0
}

func (x *PerformanceMetrics) GetBytesSaved() int64 {
	if x != nil {
		return x.BytesSaved
	}
	return 0
}

func (x *PerformanceMetrics) GetCompressionTimeNs() int64 {
	if x != nil {
		return x.CompressionTimeNs
	}
	return 0
}

func (x *PerformanceMetrics) GetDecompressionTimeNs() int64 {
	if x != nil {
		return x.DecompressionTimeNs
	}
	return 0
}

func (x *PerformanceMetrics) GetTotalRetryAttempts() int64 {
	if x != nil {
		return x.TotalRetryAttempts
	}
	return 0
}

func (x *PerformanceMetrics) GetSuccessfulRetries() int64 {
	if x != nil {
		return x.SuccessfulRetries
	}
	return 0
}

func (x *PerformanceMetrics) GetFailedRetries() int64 {
	if x != nil {
		return x.FailedRetries
	}
	return 0
}

func (x *PerformanceMetrics) GetRetrySuccessRate() float64 {
	if x != nil {
		return x.RetrySuccessRate
	}
	return 0
}

func (x *PerformanceMetrics) GetPoolUtilization() float64 {
	if x != nil {
		return x.PoolUtilization
	}
	return 0
}

func (x *PerformanceMetrics) GetIdleConnections() int64 {
	if x != nil {
		return x.IdleConnections
	}
	return 0
}

func (x *PerformanceMetrics) GetConnectionResets() int64 {
	if x != nil {
		return x.ConnectionResets
	}
	return 0
}

func (x *PerformanceMetrics) GetMemoryUsageBytes() int64 {
	if x != nil {
		return x.MemoryUsageBytes
	}
	return 0
}

func (x *PerformanceMetrics) GetBufferPoolSize() int64 {
	if x != nil {
		return x.BufferPoolSize
	}
	return 0
}

func (x *PerformanceMetrics) GetBufferPoolHits() int64 {
	if x != nil {
		return x.BufferPoolHits
	}
	return 0
}

func (x *PerformanceMetrics) GetBufferPoolMisses() int64 {
	if x != nil {
		return x.BufferPoolMisses
	}
	return 0
}

func (x *PerformanceMetrics) GetLastUpdated() int64 {
	if x != nil {
		return x.LastUpdated
	}
	return 0
}

func (x *PerformanceMetrics) GetCollectionIntervalNs() int64 {
	if x != nil {
		return x.CollectionIntervalNs
	}
	return 0
}

func (x *PerformanceMetrics) GetRuntimeStats() map[string]*ProjectRuntimeStats {
	if x != nil {
		return x.RuntimeStats
	}
	return nil
}

// MessageStatistics contains detailed message flow statistics
type MessageStatistics struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Packet statistics (1-10)
	PacketsSent     int64   `protobuf:"varint,1,opt,name=packets_sent,json=packetsSent,proto3" json:"packets_sent,omitempty"`
	PacketsReceived int64   `protobuf:"varint,2,opt,name=packets_received,json=packetsReceived,proto3" json:"packets_received,omitempty"`
	PacketsDropped  int64   `protobuf:"varint,3,opt,name=packets_dropped,json=packetsDropped,proto3" json:"packets_dropped,omitempty"`
	PacketBytes     int64   `protobuf:"varint,4,opt,name=packet_bytes,json=packetBytes,proto3" json:"packet_bytes,omitempty"`
	AvgPacketSize   float64 `protobuf:"fixed64,5,opt,name=avg_packet_size,json=avgPacketSize,proto3" json:"avg_packet_size,omitempty"` // bytes
	// Control message statistics (11-20)
	ControlMessagesSent     int64 `protobuf:"varint,11,opt,name=control_messages_sent,json=controlMessagesSent,proto3" json:"control_messages_sent,omitempty"`
	ControlMessagesReceived int64 `protobuf:"varint,12,opt,name=control_messages_received,json=controlMessagesReceived,proto3" json:"control_messages_received,omitempty"`
	ControlMessageBytes     int64 `protobuf:"varint,13,opt,name=control_message_bytes,json=controlMessageBytes,proto3" json:"control_message_bytes,omitempty"`
	// Message breakdown (21-30)
	MessagesByType map[string]int64 `protobuf:"bytes,21,rep,name=messages_by_type,json=messagesByType,proto3" json:"messages_by_type,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	// Throughput metrics (31-40)
	PacketsPerSecond float64 `protobuf:"fixed64,31,opt,name=packets_per_second,json=packetsPerSecond,proto3" json:"packets_per_second,omitempty"`
	BytesPerSecond   float64 `protobuf:"fixed64,32,opt,name=bytes_per_second,json=bytesPerSecond,proto3" json:"bytes_per_second,omitempty"`
	// Quality metrics (41-50)
	PacketLossRate      float64 `protobuf:"fixed64,41,opt,name=packet_loss_rate,json=packetLossRate,proto3" json:"packet_loss_rate,omitempty"`                // percentage
	MessageDeliveryRate float64 `protobuf:"fixed64,42,opt,name=message_delivery_rate,json=messageDeliveryRate,proto3" json:"message_delivery_rate,omitempty"` // percentage
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *MessageStatistics) Reset() {
	*x = MessageStatistics{}
	mi := &file_gravity_metrics_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageStatistics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageStatistics) ProtoMessage() {}

func (x *MessageStatistics) ProtoReflect() protoreflect.Message {
	mi := &file_gravity_metrics_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageStatistics.ProtoReflect.Descriptor instead.
func (*MessageStatistics) Descriptor() ([]byte, []int) {
	return file_gravity_metrics_proto_rawDescGZIP(), []int{3}
}

func (x *MessageStatistics) GetPacketsSent() int64 {
	if x != nil {
		return x.PacketsSent
	}
	return 0
}

func (x *MessageStatistics) GetPacketsReceived() int64 {
	if x != nil {
		return x.PacketsReceived
	}
	return 0
}

func (x *MessageStatistics) GetPacketsDropped() int64 {
	if x != nil {
		return x.PacketsDropped
	}
	return 0
}

func (x *MessageStatistics) GetPacketBytes() int64 {
	if x != nil {
		return x.PacketBytes
	}
	return 0
}

func (x *MessageStatistics) GetAvgPacketSize() float64 {
	if x != nil {
		return x.AvgPacketSize
	}
	return 0
}

func (x *MessageStatistics) GetControlMessagesSent() int64 {
	if x != nil {
		return x.ControlMessagesSent
	}
	return 0
}

func (x *MessageStatistics) GetControlMessagesReceived() int64 {
	if x != nil {
		return x.ControlMessagesReceived
	}
	return 0
}

func (x *MessageStatistics) GetControlMessageBytes() int64 {
	if x != nil {
		return x.ControlMessageBytes
	}
	return 0
}

func (x *MessageStatistics) GetMessagesByType() map[string]int64 {
	if x != nil {
		return x.MessagesByType
	}
	return nil
}

func (x *MessageStatistics) GetPacketsPerSecond() float64 {
	if x != nil {
		return x.PacketsPerSecond
	}
	return 0
}

func (x *MessageStatistics) GetBytesPerSecond() float64 {
	if x != nil {
		return x.BytesPerSecond
	}
	return 0
}

func (x *MessageStatistics) GetPacketLossRate() float64 {
	if x != nil {
		return x.PacketLossRate
	}
	return 0
}

func (x *MessageStatistics) GetMessageDeliveryRate() float64 {
	if x != nil {
		return x.MessageDeliveryRate
	}
	return 0
}

// SystemResourceMetrics contains system resource utilization
type SystemResourceMetrics struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Memory metrics (1-10)
	MemoryUsageBytes int64   `protobuf:"varint,1,opt,name=memory_usage_bytes,json=memoryUsageBytes,proto3" json:"memory_usage_bytes,omitempty"`
	MemoryUsageMb    float64 `protobuf:"fixed64,2,opt,name=memory_usage_mb,json=memoryUsageMb,proto3" json:"memory_usage_mb,omitempty"`
	AllocatedMemory  int64   `protobuf:"varint,3,opt,name=allocated_memory,json=allocatedMemory,proto3" json:"allocated_memory,omitempty"`
	GcPauseTimeNs    int64   `protobuf:"varint,4,opt,name=gc_pause_time_ns,json=gcPauseTimeNs,proto3" json:"gc_pause_time_ns,omitempty"`
	NumGoroutines    int32   `protobuf:"varint,5,opt,name=num_goroutines,json=numGoroutines,proto3" json:"num_goroutines,omitempty"`
	// CPU metrics (11-20)
	CpuUsagePercent float64 `protobuf:"fixed64,11,opt,name=cpu_usage_percent,json=cpuUsagePercent,proto3" json:"cpu_usage_percent,omitempty"`
	// Buffer pool metrics (21-30)
	BufferPoolSize    int64   `protobuf:"varint,21,opt,name=buffer_pool_size,json=bufferPoolSize,proto3" json:"buffer_pool_size,omitempty"`
	BufferPoolHits    int64   `protobuf:"varint,22,opt,name=buffer_pool_hits,json=bufferPoolHits,proto3" json:"buffer_pool_hits,omitempty"`
	BufferPoolMisses  int64   `protobuf:"varint,23,opt,name=buffer_pool_misses,json=bufferPoolMisses,proto3" json:"buffer_pool_misses,omitempty"`
	BufferPoolHitRate float64 `protobuf:"fixed64,24,opt,name=buffer_pool_hit_rate,json=bufferPoolHitRate,proto3" json:"buffer_pool_hit_rate,omitempty"` // percentage
	// File descriptor metrics (31-40)
	OpenFileDescriptors int32 `protobuf:"varint,31,opt,name=open_file_descriptors,json=openFileDescriptors,proto3" json:"open_file_descriptors,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *SystemResourceMetrics) Reset() {
	*x = SystemResourceMetrics{}
	mi := &file_gravity_metrics_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SystemResourceMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemResourceMetrics) ProtoMessage() {}

func (x *SystemResourceMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_gravity_metrics_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemResourceMetrics.ProtoReflect.Descriptor instead.
func (*SystemResourceMetrics) Descriptor() ([]byte, []int) {
	return file_gravity_metrics_proto_rawDescGZIP(), []int{4}
}

func (x *SystemResourceMetrics) GetMemoryUsageBytes() int64 {
	if x != nil {
		return x.MemoryUsageBytes
	}
	return 0
}

func (x *SystemResourceMetrics) GetMemoryUsageMb() float64 {
	if x != nil {
		return x.MemoryUsageMb
	}
	return 0
}

func (x *SystemResourceMetrics) GetAllocatedMemory() int64 {
	if x != nil {
		return x.AllocatedMemory
	}
	return 0
}

func (x *SystemResourceMetrics) GetGcPauseTimeNs() int64 {
	if x != nil {
		return x.GcPauseTimeNs
	}
	return 0
}

func (x *SystemResourceMetrics) GetNumGoroutines() int32 {
	if x != nil {
		return x.NumGoroutines
	}
	return 0
}

func (x *SystemResourceMetrics) GetCpuUsagePercent() float64 {
	if x != nil {
		return x.CpuUsagePercent
	}
	return 0
}

func (x *SystemResourceMetrics) GetBufferPoolSize() int64 {
	if x != nil {
		return x.BufferPoolSize
	}
	return 0
}

func (x *SystemResourceMetrics) GetBufferPoolHits() int64 {
	if x != nil {
		return x.BufferPoolHits
	}
	return 0
}

func (x *SystemResourceMetrics) GetBufferPoolMisses() int64 {
	if x != nil {
		return x.BufferPoolMisses
	}
	return 0
}

func (x *SystemResourceMetrics) GetBufferPoolHitRate() float64 {
	if x != nil {
		return x.BufferPoolHitRate
	}
	return 0
}

func (x *SystemResourceMetrics) GetOpenFileDescriptors() int32 {
	if x != nil {
		return x.OpenFileDescriptors
	}
	return 0
}

// HistoricalMetrics contains time-series data for trend analysis
type HistoricalMetrics struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Recent throughput samples (last 60 samples, 1 per minute)
	ThroughputHistory []*ThroughputSample `protobuf:"bytes,1,rep,name=throughput_history,json=throughputHistory,proto3" json:"throughput_history,omitempty"`
	// Recent latency samples
	LatencyHistory []*LatencySample `protobuf:"bytes,2,rep,name=latency_history,json=latencyHistory,proto3" json:"latency_history,omitempty"`
	// Error rate samples
	ErrorRateHistory []*ErrorRateSample `protobuf:"bytes,3,rep,name=error_rate_history,json=errorRateHistory,proto3" json:"error_rate_history,omitempty"`
	// Connection health samples
	HealthHistory []*HealthSample `protobuf:"bytes,4,rep,name=health_history,json=healthHistory,proto3" json:"health_history,omitempty"`
	// Maximum history length
	MaxHistoryLength int32 `protobuf:"varint,5,opt,name=max_history_length,json=maxHistoryLength,proto3" json:"max_history_length,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *HistoricalMetrics) Reset() {
	*x = HistoricalMetrics{}
	mi := &file_gravity_metrics_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HistoricalMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HistoricalMetrics) ProtoMessage() {}

func (x *HistoricalMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_gravity_metrics_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HistoricalMetrics.ProtoReflect.Descriptor instead.
func (*HistoricalMetrics) Descriptor() ([]byte, []int) {
	return file_gravity_metrics_proto_rawDescGZIP(), []int{5}
}

func (x *HistoricalMetrics) GetThroughputHistory() []*ThroughputSample {
	if x != nil {
		return x.ThroughputHistory
	}
	return nil
}

func (x *HistoricalMetrics) GetLatencyHistory() []*LatencySample {
	if x != nil {
		return x.LatencyHistory
	}
	return nil
}

func (x *HistoricalMetrics) GetErrorRateHistory() []*ErrorRateSample {
	if x != nil {
		return x.ErrorRateHistory
	}
	return nil
}

func (x *HistoricalMetrics) GetHealthHistory() []*HealthSample {
	if x != nil {
		return x.HealthHistory
	}
	return nil
}

func (x *HistoricalMetrics) GetMaxHistoryLength() int32 {
	if x != nil {
		return x.MaxHistoryLength
	}
	return 0
}

// ThroughputSample represents a throughput measurement at a point in time
type ThroughputSample struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Timestamp      int64                  `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"` // epoch milliseconds
	PacketsPerSec  float64                `protobuf:"fixed64,2,opt,name=packets_per_sec,json=packetsPerSec,proto3" json:"packets_per_sec,omitempty"`
	BytesPerSec    float64                `protobuf:"fixed64,3,opt,name=bytes_per_sec,json=bytesPerSec,proto3" json:"bytes_per_sec,omitempty"`
	MessagesPerSec float64                `protobuf:"fixed64,4,opt,name=messages_per_sec,json=messagesPerSec,proto3" json:"messages_per_sec,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ThroughputSample) Reset() {
	*x = ThroughputSample{}
	mi := &file_gravity_metrics_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ThroughputSample) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ThroughputSample) ProtoMessage() {}

func (x *ThroughputSample) ProtoReflect() protoreflect.Message {
	mi := &file_gravity_metrics_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ThroughputSample.ProtoReflect.Descriptor instead.
func (*ThroughputSample) Descriptor() ([]byte, []int) {
	return file_gravity_metrics_proto_rawDescGZIP(), []int{6}
}

func (x *ThroughputSample) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *ThroughputSample) GetPacketsPerSec() float64 {
	if x != nil {
		return x.PacketsPerSec
	}
	return 0
}

func (x *ThroughputSample) GetBytesPerSec() float64 {
	if x != nil {
		return x.BytesPerSec
	}
	return 0
}

func (x *ThroughputSample) GetMessagesPerSec() float64 {
	if x != nil {
		return x.MessagesPerSec
	}
	return 0
}

// LatencySample represents latency measurements at a point in time
type LatencySample struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     int64                  `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"` // epoch milliseconds
	AvgLatencyNs  int64                  `protobuf:"varint,2,opt,name=avg_latency_ns,json=avgLatencyNs,proto3" json:"avg_latency_ns,omitempty"`
	P95LatencyNs  int64                  `protobuf:"varint,3,opt,name=p95_latency_ns,json=p95LatencyNs,proto3" json:"p95_latency_ns,omitempty"`
	P99LatencyNs  int64                  `protobuf:"varint,4,opt,name=p99_latency_ns,json=p99LatencyNs,proto3" json:"p99_latency_ns,omitempty"`
	MaxLatencyNs  int64                  `protobuf:"varint,5,opt,name=max_latency_ns,json=maxLatencyNs,proto3" json:"max_latency_ns,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LatencySample) Reset() {
	*x = LatencySample{}
	mi := &file_gravity_metrics_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LatencySample) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LatencySample) ProtoMessage() {}

func (x *LatencySample) ProtoReflect() protoreflect.Message {
	mi := &file_gravity_metrics_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LatencySample.ProtoReflect.Descriptor instead.
func (*LatencySample) Descriptor() ([]byte, []int) {
	return file_gravity_metrics_proto_rawDescGZIP(), []int{7}
}

func (x *LatencySample) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *LatencySample) GetAvgLatencyNs() int64 {
	if x != nil {
		return x.AvgLatencyNs
	}
	return 0
}

func (x *LatencySample) GetP95LatencyNs() int64 {
	if x != nil {
		return x.P95LatencyNs
	}
	return 0
}

func (x *LatencySample) GetP99LatencyNs() int64 {
	if x != nil {
		return x.P99LatencyNs
	}
	return 0
}

func (x *LatencySample) GetMaxLatencyNs() int64 {
	if x != nil {
		return x.MaxLatencyNs
	}
	return 0
}

// ErrorRateSample represents error rate at a point in time
type ErrorRateSample struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     int64                  `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                   // epoch milliseconds
	ErrorRate     float64                `protobuf:"fixed64,2,opt,name=error_rate,json=errorRate,proto3" json:"error_rate,omitempty"` // percentage
	TotalErrors   int64                  `protobuf:"varint,3,opt,name=total_errors,json=totalErrors,proto3" json:"total_errors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorRateSample) Reset() {
	*x = ErrorRateSample{}
	mi := &file_gravity_metrics_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorRateSample) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorRateSample) ProtoMessage() {}

func (x *ErrorRateSample) ProtoReflect() protoreflect.Message {
	mi := &file_gravity_metrics_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorRateSample.ProtoReflect.Descriptor instead.
func (*ErrorRateSample) Descriptor() ([]byte, []int) {
	return file_gravity_metrics_proto_rawDescGZIP(), []int{8}
}

func (x *ErrorRateSample) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *ErrorRateSample) GetErrorRate() float64 {
	if x != nil {
		return x.ErrorRate
	}
	return 0
}

func (x *ErrorRateSample) GetTotalErrors() int64 {
	if x != nil {
		return x.TotalErrors
	}
	return 0
}

// HealthSample represents system health at a point in time
type HealthSample struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Timestamp         int64                  `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"` // epoch milliseconds
	HealthyStreams    int32                  `protobuf:"varint,2,opt,name=healthy_streams,json=healthyStreams,proto3" json:"healthy_streams,omitempty"`
	TotalStreams      int32                  `protobuf:"varint,3,opt,name=total_streams,json=totalStreams,proto3" json:"total_streams,omitempty"`
	ActiveConnections int32                  `protobuf:"varint,4,opt,name=active_connections,json=activeConnections,proto3" json:"active_connections,omitempty"`
	HealthScore       float64                `protobuf:"fixed64,5,opt,name=health_score,json=healthScore,proto3" json:"health_score,omitempty"` // percentage
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *HealthSample) Reset() {
	*x = HealthSample{}
	mi := &file_gravity_metrics_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthSample) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthSample) ProtoMessage() {}

func (x *HealthSample) ProtoReflect() protoreflect.Message {
	mi := &file_gravity_metrics_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthSample.ProtoReflect.Descriptor instead.
func (*HealthSample) Descriptor() ([]byte, []int) {
	return file_gravity_metrics_proto_rawDescGZIP(), []int{9}
}

func (x *HealthSample) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *HealthSample) GetHealthyStreams() int32 {
	if x != nil {
		return x.HealthyStreams
	}
	return 0
}

func (x *HealthSample) GetTotalStreams() int32 {
	if x != nil {
		return x.TotalStreams
	}
	return 0
}

func (x *HealthSample) GetActiveConnections() int32 {
	if x != nil {
		return x.ActiveConnections
	}
	return 0
}

func (x *HealthSample) GetHealthScore() float64 {
	if x != nil {
		return x.HealthScore
	}
	return 0
}

// ProjectRuntimeStats contains real-time project runtime statistics
type ProjectRuntimeStats struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Runtime identity (1-10)
	RuntimeId    string `protobuf:"bytes,1,opt,name=runtime_id,json=runtimeId,proto3" json:"runtime_id,omitempty"`
	RuntimeName  string `protobuf:"bytes,2,opt,name=runtime_name,json=runtimeName,proto3" json:"runtime_name,omitempty"`
	Image        string `protobuf:"bytes,3,opt,name=image,proto3" json:"image,omitempty"`
	DeploymentId string `protobuf:"bytes,4,opt,name=deployment_id,json=deploymentId,proto3" json:"deployment_id,omitempty"`
	// Runtime state (11-20)
	Status       string `protobuf:"bytes,11,opt,name=status,proto3" json:"status,omitempty"`
	Paused       bool   `protobuf:"varint,12,opt,name=paused,proto3" json:"paused,omitempty"`
	PausedTime   int64  `protobuf:"varint,13,opt,name=paused_time,json=pausedTime,proto3" json:"paused_time,omitempty"`    // epoch milliseconds, 0 if not paused
	StartedTime  int64  `protobuf:"varint,14,opt,name=started_time,json=startedTime,proto3" json:"started_time,omitempty"` // epoch milliseconds
	RestartCount int64  `protobuf:"varint,15,opt,name=restart_count,json=restartCount,proto3" json:"restart_count,omitempty"`
	// CPU metrics (21-30)
	CpuUsagePercent     float64 `protobuf:"fixed64,21,opt,name=cpu_usage_percent,json=cpuUsagePercent,proto3" json:"cpu_usage_percent,omitempty"`
	CpuUsageTotalNs     uint64  `protobuf:"varint,22,opt,name=cpu_usage_total_ns,json=cpuUsageTotalNs,proto3" json:"cpu_usage_total_ns,omitempty"`
	CpuUsageKernelNs    uint64  `protobuf:"varint,23,opt,name=cpu_usage_kernel_ns,json=cpuUsageKernelNs,proto3" json:"cpu_usage_kernel_ns,omitempty"`
	CpuUsageUserNs      uint64  `protobuf:"varint,24,opt,name=cpu_usage_user_ns,json=cpuUsageUserNs,proto3" json:"cpu_usage_user_ns,omitempty"`
	CpuThrottledPeriods uint64  `protobuf:"varint,25,opt,name=cpu_throttled_periods,json=cpuThrottledPeriods,proto3" json:"cpu_throttled_periods,omitempty"`
	CpuThrottledTimeNs  uint64  `protobuf:"varint,26,opt,name=cpu_throttled_time_ns,json=cpuThrottledTimeNs,proto3" json:"cpu_throttled_time_ns,omitempty"`
	CpuLimit            float64 `protobuf:"fixed64,27,opt,name=cpu_limit,json=cpuLimit,proto3" json:"cpu_limit,omitempty"`
	// Memory metrics (31-40)
	MemoryUsageBytes     uint64  `protobuf:"varint,31,opt,name=memory_usage_bytes,json=memoryUsageBytes,proto3" json:"memory_usage_bytes,omitempty"`
	MemoryLimitBytes     uint64  `protobuf:"varint,32,opt,name=memory_limit_bytes,json=memoryLimitBytes,proto3" json:"memory_limit_bytes,omitempty"`
	MemoryUsagePercent   float64 `protobuf:"fixed64,33,opt,name=memory_usage_percent,json=memoryUsagePercent,proto3" json:"memory_usage_percent,omitempty"`
	MemoryMaxUsageBytes  uint64  `protobuf:"varint,34,opt,name=memory_max_usage_bytes,json=memoryMaxUsageBytes,proto3" json:"memory_max_usage_bytes,omitempty"`
	MemoryCacheBytes     uint64  `protobuf:"varint,35,opt,name=memory_cache_bytes,json=memoryCacheBytes,proto3" json:"memory_cache_bytes,omitempty"`
	MemoryRssBytes       uint64  `protobuf:"varint,36,opt,name=memory_rss_bytes,json=memoryRssBytes,proto3" json:"memory_rss_bytes,omitempty"`
	MemorySwapBytes      uint64  `protobuf:"varint,37,opt,name=memory_swap_bytes,json=memorySwapBytes,proto3" json:"memory_swap_bytes,omitempty"`
	MemorySwapLimitBytes uint64  `protobuf:"varint,38,opt,name=memory_swap_limit_bytes,json=memorySwapLimitBytes,proto3" json:"memory_swap_limit_bytes,omitempty"`
	OomKills             uint64  `protobuf:"varint,39,opt,name=oom_kills,json=oomKills,proto3" json:"oom_kills,omitempty"`
	// Network metrics (41-50)
	NetworkRxBytes   uint64 `protobuf:"varint,41,opt,name=network_rx_bytes,json=networkRxBytes,proto3" json:"network_rx_bytes,omitempty"`
	NetworkTxBytes   uint64 `protobuf:"varint,42,opt,name=network_tx_bytes,json=networkTxBytes,proto3" json:"network_tx_bytes,omitempty"`
	NetworkRxPackets uint64 `protobuf:"varint,43,opt,name=network_rx_packets,json=networkRxPackets,proto3" json:"network_rx_packets,omitempty"`
	NetworkTxPackets uint64 `protobuf:"varint,44,opt,name=network_tx_packets,json=networkTxPackets,proto3" json:"network_tx_packets,omitempty"`
	NetworkRxErrors  uint64 `protobuf:"varint,45,opt,name=network_rx_errors,json=networkRxErrors,proto3" json:"network_rx_errors,omitempty"`
	NetworkTxErrors  uint64 `protobuf:"varint,46,opt,name=network_tx_errors,json=networkTxErrors,proto3" json:"network_tx_errors,omitempty"`
	NetworkRxDropped uint64 `protobuf:"varint,47,opt,name=network_rx_dropped,json=networkRxDropped,proto3" json:"network_rx_dropped,omitempty"`
	NetworkTxDropped uint64 `protobuf:"varint,48,opt,name=network_tx_dropped,json=networkTxDropped,proto3" json:"network_tx_dropped,omitempty"`
	// Disk I/O metrics (51-60)
	BlockIoReadBytes  uint64 `protobuf:"varint,51,opt,name=block_io_read_bytes,json=blockIoReadBytes,proto3" json:"block_io_read_bytes,omitempty"`
	BlockIoWriteBytes uint64 `protobuf:"varint,52,opt,name=block_io_write_bytes,json=blockIoWriteBytes,proto3" json:"block_io_write_bytes,omitempty"`
	BlockIoReadOps    uint64 `protobuf:"varint,53,opt,name=block_io_read_ops,json=blockIoReadOps,proto3" json:"block_io_read_ops,omitempty"`
	BlockIoWriteOps   uint64 `protobuf:"varint,54,opt,name=block_io_write_ops,json=blockIoWriteOps,proto3" json:"block_io_write_ops,omitempty"`
	// Process metrics (61-70)
	PidsCurrent uint64 `protobuf:"varint,61,opt,name=pids_current,json=pidsCurrent,proto3" json:"pids_current,omitempty"`
	PidsLimit   uint64 `protobuf:"varint,62,opt,name=pids_limit,json=pidsLimit,proto3" json:"pids_limit,omitempty"`
	// Network interface information (71-80)
	Ipv4Address string `protobuf:"bytes,71,opt,name=ipv4_address,json=ipv4Address,proto3" json:"ipv4_address,omitempty"`
	Ipv6Address string `protobuf:"bytes,72,opt,name=ipv6_address,json=ipv6Address,proto3" json:"ipv6_address,omitempty"`
	Hostname    string `protobuf:"bytes,73,opt,name=hostname,proto3" json:"hostname,omitempty"`
	// Runtime metrics (81-90)
	InflightRequests int64 `protobuf:"varint,81,opt,name=inflight_requests,json=inflightRequests,proto3" json:"inflight_requests,omitempty"`
	// Health and timing (91-100)
	Healthy       bool  `protobuf:"varint,91,opt,name=healthy,proto3" json:"healthy,omitempty"`
	LastUpdated   int64 `protobuf:"varint,92,opt,name=last_updated,json=lastUpdated,proto3" json:"last_updated,omitempty"` // epoch milliseconds
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProjectRuntimeStats) Reset() {
	*x = ProjectRuntimeStats{}
	mi := &file_gravity_metrics_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectRuntimeStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectRuntimeStats) ProtoMessage() {}

func (x *ProjectRuntimeStats) ProtoReflect() protoreflect.Message {
	mi := &file_gravity_metrics_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectRuntimeStats.ProtoReflect.Descriptor instead.
func (*ProjectRuntimeStats) Descriptor() ([]byte, []int) {
	return file_gravity_metrics_proto_rawDescGZIP(), []int{10}
}

func (x *ProjectRuntimeStats) GetRuntimeId() string {
	if x != nil {
		return x.RuntimeId
	}
	return ""
}

func (x *ProjectRuntimeStats) GetRuntimeName() string {
	if x != nil {
		return x.RuntimeName
	}
	return ""
}

func (x *ProjectRuntimeStats) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *ProjectRuntimeStats) GetDeploymentId() string {
	if x != nil {
		return x.DeploymentId
	}
	return ""
}

func (x *ProjectRuntimeStats) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ProjectRuntimeStats) GetPaused() bool {
	if x != nil {
		return x.Paused
	}
	return false
}

func (x *ProjectRuntimeStats) GetPausedTime() int64 {
	if x != nil {
		return x.PausedTime
	}
	return 0
}

func (x *ProjectRuntimeStats) GetStartedTime() int64 {
	if x != nil {
		return x.StartedTime
	}
	return 0
}

func (x *ProjectRuntimeStats) GetRestartCount() int64 {
	if x != nil {
		return x.RestartCount
	}
	return 0
}

func (x *ProjectRuntimeStats) GetCpuUsagePercent() float64 {
	if x != nil {
		return x.CpuUsagePercent
	}
	return 0
}

func (x *ProjectRuntimeStats) GetCpuUsageTotalNs() uint64 {
	if x != nil {
		return x.CpuUsageTotalNs
	}
	return 0
}

func (x *ProjectRuntimeStats) GetCpuUsageKernelNs() uint64 {
	if x != nil {
		return x.CpuUsageKernelNs
	}
	return 0
}

func (x *ProjectRuntimeStats) GetCpuUsageUserNs() uint64 {
	if x != nil {
		return x.CpuUsageUserNs
	}
	return 0
}

func (x *ProjectRuntimeStats) GetCpuThrottledPeriods() uint64 {
	if x != nil {
		return x.CpuThrottledPeriods
	}
	return 0
}

func (x *ProjectRuntimeStats) GetCpuThrottledTimeNs() uint64 {
	if x != nil {
		return x.CpuThrottledTimeNs
	}
	return 0
}

func (x *ProjectRuntimeStats) GetCpuLimit() float64 {
	if x != nil {
		return x.CpuLimit
	}
	return 0
}

func (x *ProjectRuntimeStats) GetMemoryUsageBytes() uint64 {
	if x != nil {
		return x.MemoryUsageBytes
	}
	return 0
}

func (x *ProjectRuntimeStats) GetMemoryLimitBytes() uint64 {
	if x != nil {
		return x.MemoryLimitBytes
	}
	return 0
}

func (x *ProjectRuntimeStats) GetMemoryUsagePercent() float64 {
	if x != nil {
		return x.MemoryUsagePercent
	}
	return 0
}

func (x *ProjectRuntimeStats) GetMemoryMaxUsageBytes() uint64 {
	if x != nil {
		return x.MemoryMaxUsageBytes
	}
	return 0
}

func (x *ProjectRuntimeStats) GetMemoryCacheBytes() uint64 {
	if x != nil {
		return x.MemoryCacheBytes
	}
	return 0
}

func (x *ProjectRuntimeStats) GetMemoryRssBytes() uint64 {
	if x != nil {
		return x.MemoryRssBytes
	}
	return 0
}

func (x *ProjectRuntimeStats) GetMemorySwapBytes() uint64 {
	if x != nil {
		return x.MemorySwapBytes
	}
	return 0
}

func (x *ProjectRuntimeStats) GetMemorySwapLimitBytes() uint64 {
	if x != nil {
		return x.MemorySwapLimitBytes
	}
	return 0
}

func (x *ProjectRuntimeStats) GetOomKills() uint64 {
	if x != nil {
		return x.OomKills
	}
	return 0
}

func (x *ProjectRuntimeStats) GetNetworkRxBytes() uint64 {
	if x != nil {
		return x.NetworkRxBytes
	}
	return 0
}

func (x *ProjectRuntimeStats) GetNetworkTxBytes() uint64 {
	if x != nil {
		return x.NetworkTxBytes
	}
	return 0
}

func (x *ProjectRuntimeStats) GetNetworkRxPackets() uint64 {
	if x != nil {
		return x.NetworkRxPackets
	}
	return 0
}

func (x *ProjectRuntimeStats) GetNetworkTxPackets() uint64 {
	if x != nil {
		return x.NetworkTxPackets
	}
	return 0
}

func (x *ProjectRuntimeStats) GetNetworkRxErrors() uint64 {
	if x != nil {
		return x.NetworkRxErrors
	}
	return 0
}

func (x *ProjectRuntimeStats) GetNetworkTxErrors() uint64 {
	if x != nil {
		return x.NetworkTxErrors
	}
	return 0
}

func (x *ProjectRuntimeStats) GetNetworkRxDropped() uint64 {
	if x != nil {
		return x.NetworkRxDropped
	}
	return 0
}

func (x *ProjectRuntimeStats) GetNetworkTxDropped() uint64 {
	if x != nil {
		return x.NetworkTxDropped
	}
	return 0
}

func (x *ProjectRuntimeStats) GetBlockIoReadBytes() uint64 {
	if x != nil {
		return x.BlockIoReadBytes
	}
	return 0
}

func (x *ProjectRuntimeStats) GetBlockIoWriteBytes() uint64 {
	if x != nil {
		return x.BlockIoWriteBytes
	}
	return 0
}

func (x *ProjectRuntimeStats) GetBlockIoReadOps() uint64 {
	if x != nil {
		return x.BlockIoReadOps
	}
	return 0
}

func (x *ProjectRuntimeStats) GetBlockIoWriteOps() uint64 {
	if x != nil {
		return x.BlockIoWriteOps
	}
	return 0
}

func (x *ProjectRuntimeStats) GetPidsCurrent() uint64 {
	if x != nil {
		return x.PidsCurrent
	}
	return 0
}

func (x *ProjectRuntimeStats) GetPidsLimit() uint64 {
	if x != nil {
		return x.PidsLimit
	}
	return 0
}

func (x *ProjectRuntimeStats) GetIpv4Address() string {
	if x != nil {
		return x.Ipv4Address
	}
	return ""
}

func (x *ProjectRuntimeStats) GetIpv6Address() string {
	if x != nil {
		return x.Ipv6Address
	}
	return ""
}

func (x *ProjectRuntimeStats) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *ProjectRuntimeStats) GetInflightRequests() int64 {
	if x != nil {
		return x.InflightRequests
	}
	return 0
}

func (x *ProjectRuntimeStats) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *ProjectRuntimeStats) GetLastUpdated() int64 {
	if x != nil {
		return x.LastUpdated
	}
	return 0
}

var File_gravity_metrics_proto protoreflect.FileDescriptor

const file_gravity_metrics_proto_rawDesc = "" +
	"\n" +
	"\x15gravity_metrics.proto\x12\agravity\"\xe1\x04\n" +
	"\rServerMetrics\x12\x1d\n" +
	"\n" +
	"start_time\x18\x01 \x01(\x03R\tstartTime\x12\x16\n" +
	"\x06uptime\x18\x02 \x01(\x04R\x06uptime\x12%\n" +
	"\x0econnected_time\x18\x03 \x01(\x03R\rconnectedTime\x12*\n" +
	"\x11last_message_time\x18\x04 \x01(\x03R\x0flastMessageTime\x12!\n" +
	"\fis_connected\x18\v \x01(\bR\visConnected\x12'\n" +
	"\x0freconnect_count\x18\f \x01(\x03R\x0ereconnectCount\x12+\n" +
	"\x11total_connections\x18\r \x01(\x03R\x10totalConnections\x12A\n" +
	"\fgrpc_metrics\x18\x15 \x01(\v2\x1e.gravity.GRPCConnectionMetricsR\vgrpcMetrics\x12=\n" +
	"\vperformance\x18\x16 \x01(\v2\x1b.gravity.PerformanceMetricsR\vperformance\x12?\n" +
	"\rmessage_stats\x18\x17 \x01(\v2\x1a.gravity.MessageStatisticsR\fmessageStats\x12E\n" +
	"\x0esystem_metrics\x18\x18 \x01(\v2\x1e.gravity.SystemResourceMetricsR\rsystemMetrics\x12C\n" +
	"\x0fhistorical_data\x18) \x01(\v2\x1a.gravity.HistoricalMetricsR\x0ehistoricalData\"\xeb\x05\n" +
	"\x15GRPCConnectionMetrics\x12\x1b\n" +
	"\tpool_size\x18\x01 \x01(\x05R\bpoolSize\x12-\n" +
	"\x12active_connections\x18\x02 \x01(\x05R\x11activeConnections\x12)\n" +
	"\x10idle_connections\x18\x03 \x01(\x05R\x0fidleConnections\x12-\n" +
	"\x12failed_connections\x18\x04 \x01(\x05R\x11failedConnections\x12+\n" +
	"\x11connection_states\x18\x05 \x03(\tR\x10connectionStates\x12#\n" +
	"\rtotal_streams\x18\v \x01(\x05R\ftotalStreams\x12'\n" +
	"\x0fcontrol_streams\x18\f \x01(\x05R\x0econtrolStreams\x12%\n" +
	"\x0etunnel_streams\x18\r \x01(\x05R\rtunnelStreams\x12'\n" +
	"\x0fhealthy_streams\x18\x0e \x01(\x05R\x0ehealthyStreams\x12%\n" +
	"\x0eactive_streams\x18\x0f \x01(\x05R\ractiveStreams\x12+\n" +
	"\x11stream_allocation\x18\x10 \x01(\tR\x10streamAllocation\x12)\n" +
	"\x10protocol_version\x18\x15 \x01(\tR\x0fprotocolVersion\x12/\n" +
	"\x13compression_enabled\x18\x16 \x01(\bR\x12compressionEnabled\x12\x1f\n" +
	"\vtls_version\x18\x17 \x01(\tR\n" +
	"tlsVersion\x12*\n" +
	"\x11last_health_check\x18\x1f \x01(\x03R\x0flastHealthCheck\x127\n" +
	"\x18health_check_interval_ns\x18  \x01(\x03R\x15healthCheckIntervalNs\x12+\n" +
	"\x11unhealthy_streams\x18! \x03(\tR\x10unhealthyStreams\"\x88\x0f\n" +
	"\x12PerformanceMetrics\x121\n" +
	"\x15avg_packet_latency_ns\x18\x01 \x01(\x03R\x12avgPacketLatencyNs\x121\n" +
	"\x15p95_packet_latency_ns\x18\x02 \x01(\x03R\x12p95PacketLatencyNs\x121\n" +
	"\x15p99_packet_latency_ns\x18\x03 \x01(\x03R\x12p99PacketLatencyNs\x121\n" +
	"\x15max_packet_latency_ns\x18\x04 \x01(\x03R\x12maxPacketLatencyNs\x123\n" +
	"\x16avg_control_latency_ns\x18\x05 \x01(\x03R\x13avgControlLatencyNs\x123\n" +
	"\x16p95_control_latency_ns\x18\x06 \x01(\x03R\x13p95ControlLatencyNs\x12,\n" +
	"\x12packets_per_second\x18\v \x01(\x01R\x10packetsPerSecond\x12(\n" +
	"\x10bytes_per_second\x18\f \x01(\x01R\x0ebytesPerSecond\x127\n" +
	"\x18control_messages_per_sec\x18\r \x01(\x01R\x15controlMessagesPerSec\x12\x1d\n" +
	"\n" +
	"error_rate\x18\x15 \x01(\x01R\terrorRate\x12!\n" +
	"\fpacket_drops\x18\x16 \x01(\x03R\vpacketDrops\x12#\n" +
	"\rstream_errors\x18\x17 \x01(\x03R\fstreamErrors\x12+\n" +
	"\x11connection_errors\x18\x18 \x01(\x03R\x10connectionErrors\x12'\n" +
	"\x0fhealthy_streams\x18\x1f \x01(\x03R\x0ehealthyStreams\x12#\n" +
	"\rtotal_streams\x18  \x01(\x03R\ftotalStreams\x12-\n" +
	"\x12active_connections\x18! \x01(\x03R\x11activeConnections\x12+\n" +
	"\x11unhealthy_streams\x18\" \x01(\x03R\x10unhealthyStreams\x12-\n" +
	"\x12stream_utilization\x18# \x01(\x01R\x11streamUtilization\x124\n" +
	"\x16circuit_breaker_states\x18) \x03(\tR\x14circuitBreakerStates\x120\n" +
	"\x14total_circuit_breaks\x18* \x01(\x03R\x12totalCircuitBreaks\x12/\n" +
	"\x14avg_recovery_time_ns\x18+ \x01(\x03R\x11avgRecoveryTimeNs\x12+\n" +
	"\x11compression_ratio\x183 \x01(\x01R\x10compressionRatio\x12\x1f\n" +
	"\vbytes_saved\x184 \x01(\x03R\n" +
	"bytesSaved\x12.\n" +
	"\x13compression_time_ns\x185 \x01(\x03R\x11compressionTimeNs\x122\n" +
	"\x15decompression_time_ns\x186 \x01(\x03R\x13decompressionTimeNs\x120\n" +
	"\x14total_retry_attempts\x18= \x01(\x03R\x12totalRetryAttempts\x12-\n" +
	"\x12successful_retries\x18> \x01(\x03R\x11successfulRetries\x12%\n" +
	"\x0efailed_retries\x18? \x01(\x03R\rfailedRetries\x12,\n" +
	"\x12retry_success_rate\x18@ \x01(\x01R\x10retrySuccessRate\x12)\n" +
	"\x10pool_utilization\x18G \x01(\x01R\x0fpoolUtilization\x12)\n" +
	"\x10idle_connections\x18H \x01(\x03R\x0fidleConnections\x12+\n" +
	"\x11connection_resets\x18I \x01(\x03R\x10connectionResets\x12,\n" +
	"\x12memory_usage_bytes\x18Q \x01(\x03R\x10memoryUsageBytes\x12(\n" +
	"\x10buffer_pool_size\x18R \x01(\x03R\x0ebufferPoolSize\x12(\n" +
	"\x10buffer_pool_hits\x18S \x01(\x03R\x0ebufferPoolHits\x12,\n" +
	"\x12buffer_pool_misses\x18T \x01(\x03R\x10bufferPoolMisses\x12!\n" +
	"\flast_updated\x18[ \x01(\x03R\vlastUpdated\x124\n" +
	"\x16collection_interval_ns\x18\\ \x01(\x03R\x14collectionIntervalNs\x12R\n" +
	"\rruntime_stats\x18e \x03(\v2-.gravity.PerformanceMetrics.RuntimeStatsEntryR\fruntimeStats\x1a]\n" +
	"\x11RuntimeStatsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x122\n" +
	"\x05value\x18\x02 \x01(\v2\x1c.gravity.ProjectRuntimeStatsR\x05value:\x028\x01\"\xcc\x05\n" +
	"\x11MessageStatistics\x12!\n" +
	"\fpackets_sent\x18\x01 \x01(\x03R\vpacketsSent\x12)\n" +
	"\x10packets_received\x18\x02 \x01(\x03R\x0fpacketsReceived\x12'\n" +
	"\x0fpackets_dropped\x18\x03 \x01(\x03R\x0epacketsDropped\x12!\n" +
	"\fpacket_bytes\x18\x04 \x01(\x03R\vpacketBytes\x12&\n" +
	"\x0favg_packet_size\x18\x05 \x01(\x01R\ravgPacketSize\x122\n" +
	"\x15control_messages_sent\x18\v \x01(\x03R\x13controlMessagesSent\x12:\n" +
	"\x19control_messages_received\x18\f \x01(\x03R\x17controlMessagesReceived\x122\n" +
	"\x15control_message_bytes\x18\r \x01(\x03R\x13controlMessageBytes\x12X\n" +
	"\x10messages_by_type\x18\x15 \x03(\v2..gravity.MessageStatistics.MessagesByTypeEntryR\x0emessagesByType\x12,\n" +
	"\x12packets_per_second\x18\x1f \x01(\x01R\x10packetsPerSecond\x12(\n" +
	"\x10bytes_per_second\x18  \x01(\x01R\x0ebytesPerSecond\x12(\n" +
	"\x10packet_loss_rate\x18) \x01(\x01R\x0epacketLossRate\x122\n" +
	"\x15message_delivery_rate\x18* \x01(\x01R\x13messageDeliveryRate\x1aA\n" +
	"\x13MessagesByTypeEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\"\xfb\x03\n" +
	"\x15SystemResourceMetrics\x12,\n" +
	"\x12memory_usage_bytes\x18\x01 \x01(\x03R\x10memoryUsageBytes\x12&\n" +
	"\x0fmemory_usage_mb\x18\x02 \x01(\x01R\rmemoryUsageMb\x12)\n" +
	"\x10allocated_memory\x18\x03 \x01(\x03R\x0fallocatedMemory\x12'\n" +
	"\x10gc_pause_time_ns\x18\x04 \x01(\x03R\rgcPauseTimeNs\x12%\n" +
	"\x0enum_goroutines\x18\x05 \x01(\x05R\rnumGoroutines\x12*\n" +
	"\x11cpu_usage_percent\x18\v \x01(\x01R\x0fcpuUsagePercent\x12(\n" +
	"\x10buffer_pool_size\x18\x15 \x01(\x03R\x0ebufferPoolSize\x12(\n" +
	"\x10buffer_pool_hits\x18\x16 \x01(\x03R\x0ebufferPoolHits\x12,\n" +
	"\x12buffer_pool_misses\x18\x17 \x01(\x03R\x10bufferPoolMisses\x12/\n" +
	"\x14buffer_pool_hit_rate\x18\x18 \x01(\x01R\x11bufferPoolHitRate\x122\n" +
	"\x15open_file_descriptors\x18\x1f \x01(\x05R\x13openFileDescriptors\"\xd2\x02\n" +
	"\x11HistoricalMetrics\x12H\n" +
	"\x12throughput_history\x18\x01 \x03(\v2\x19.gravity.ThroughputSampleR\x11throughputHistory\x12?\n" +
	"\x0flatency_history\x18\x02 \x03(\v2\x16.gravity.LatencySampleR\x0elatencyHistory\x12F\n" +
	"\x12error_rate_history\x18\x03 \x03(\v2\x18.gravity.ErrorRateSampleR\x10errorRateHistory\x12<\n" +
	"\x0ehealth_history\x18\x04 \x03(\v2\x15.gravity.HealthSampleR\rhealthHistory\x12,\n" +
	"\x12max_history_length\x18\x05 \x01(\x05R\x10maxHistoryLength\"\xa6\x01\n" +
	"\x10ThroughputSample\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestamp\x12&\n" +
	"\x0fpackets_per_sec\x18\x02 \x01(\x01R\rpacketsPerSec\x12\"\n" +
	"\rbytes_per_sec\x18\x03 \x01(\x01R\vbytesPerSec\x12(\n" +
	"\x10messages_per_sec\x18\x04 \x01(\x01R\x0emessagesPerSec\"\xc5\x01\n" +
	"\rLatencySample\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestamp\x12$\n" +
	"\x0eavg_latency_ns\x18\x02 \x01(\x03R\favgLatencyNs\x12$\n" +
	"\x0ep95_latency_ns\x18\x03 \x01(\x03R\fp95LatencyNs\x12$\n" +
	"\x0ep99_latency_ns\x18\x04 \x01(\x03R\fp99LatencyNs\x12$\n" +
	"\x0emax_latency_ns\x18\x05 \x01(\x03R\fmaxLatencyNs\"q\n" +
	"\x0fErrorRateSample\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestamp\x12\x1d\n" +
	"\n" +
	"error_rate\x18\x02 \x01(\x01R\terrorRate\x12!\n" +
	"\ftotal_errors\x18\x03 \x01(\x03R\vtotalErrors\"\xcc\x01\n" +
	"\fHealthSample\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestamp\x12'\n" +
	"\x0fhealthy_streams\x18\x02 \x01(\x05R\x0ehealthyStreams\x12#\n" +
	"\rtotal_streams\x18\x03 \x01(\x05R\ftotalStreams\x12-\n" +
	"\x12active_connections\x18\x04 \x01(\x05R\x11activeConnections\x12!\n" +
	"\fhealth_score\x18\x05 \x01(\x01R\vhealthScore\"\xa7\x0e\n" +
	"\x13ProjectRuntimeStats\x12\x1d\n" +
	"\n" +
	"runtime_id\x18\x01 \x01(\tR\truntimeId\x12!\n" +
	"\fruntime_name\x18\x02 \x01(\tR\vruntimeName\x12\x14\n" +
	"\x05image\x18\x03 \x01(\tR\x05image\x12#\n" +
	"\rdeployment_id\x18\x04 \x01(\tR\fdeploymentId\x12\x16\n" +
	"\x06status\x18\v \x01(\tR\x06status\x12\x16\n" +
	"\x06paused\x18\f \x01(\bR\x06paused\x12\x1f\n" +
	"\vpaused_time\x18\r \x01(\x03R\n" +
	"pausedTime\x12!\n" +
	"\fstarted_time\x18\x0e \x01(\x03R\vstartedTime\x12#\n" +
	"\rrestart_count\x18\x0f \x01(\x03R\frestartCount\x12*\n" +
	"\x11cpu_usage_percent\x18\x15 \x01(\x01R\x0fcpuUsagePercent\x12+\n" +
	"\x12cpu_usage_total_ns\x18\x16 \x01(\x04R\x0fcpuUsageTotalNs\x12-\n" +
	"\x13cpu_usage_kernel_ns\x18\x17 \x01(\x04R\x10cpuUsageKernelNs\x12)\n" +
	"\x11cpu_usage_user_ns\x18\x18 \x01(\x04R\x0ecpuUsageUserNs\x122\n" +
	"\x15cpu_throttled_periods\x18\x19 \x01(\x04R\x13cpuThrottledPeriods\x121\n" +
	"\x15cpu_throttled_time_ns\x18\x1a \x01(\x04R\x12cpuThrottledTimeNs\x12\x1b\n" +
	"\tcpu_limit\x18\x1b \x01(\x01R\bcpuLimit\x12,\n" +
	"\x12memory_usage_bytes\x18\x1f \x01(\x04R\x10memoryUsageBytes\x12,\n" +
	"\x12memory_limit_bytes\x18  \x01(\x04R\x10memoryLimitBytes\x120\n" +
	"\x14memory_usage_percent\x18! \x01(\x01R\x12memoryUsagePercent\x123\n" +
	"\x16memory_max_usage_bytes\x18\" \x01(\x04R\x13memoryMaxUsageBytes\x12,\n" +
	"\x12memory_cache_bytes\x18# \x01(\x04R\x10memoryCacheBytes\x12(\n" +
	"\x10memory_rss_bytes\x18$ \x01(\x04R\x0ememoryRssBytes\x12*\n" +
	"\x11memory_swap_bytes\x18% \x01(\x04R\x0fmemorySwapBytes\x125\n" +
	"\x17memory_swap_limit_bytes\x18& \x01(\x04R\x14memorySwapLimitBytes\x12\x1b\n" +
	"\toom_kills\x18' \x01(\x04R\boomKills\x12(\n" +
	"\x10network_rx_bytes\x18) \x01(\x04R\x0enetworkRxBytes\x12(\n" +
	"\x10network_tx_bytes\x18* \x01(\x04R\x0enetworkTxBytes\x12,\n" +
	"\x12network_rx_packets\x18+ \x01(\x04R\x10networkRxPackets\x12,\n" +
	"\x12network_tx_packets\x18, \x01(\x04R\x10networkTxPackets\x12*\n" +
	"\x11network_rx_errors\x18- \x01(\x04R\x0fnetworkRxErrors\x12*\n" +
	"\x11network_tx_errors\x18. \x01(\x04R\x0fnetworkTxErrors\x12,\n" +
	"\x12network_rx_dropped\x18/ \x01(\x04R\x10networkRxDropped\x12,\n" +
	"\x12network_tx_dropped\x180 \x01(\x04R\x10networkTxDropped\x12-\n" +
	"\x13block_io_read_bytes\x183 \x01(\x04R\x10blockIoReadBytes\x12/\n" +
	"\x14block_io_write_bytes\x184 \x01(\x04R\x11blockIoWriteBytes\x12)\n" +
	"\x11block_io_read_ops\x185 \x01(\x04R\x0eblockIoReadOps\x12+\n" +
	"\x12block_io_write_ops\x186 \x01(\x04R\x0fblockIoWriteOps\x12!\n" +
	"\fpids_current\x18= \x01(\x04R\vpidsCurrent\x12\x1d\n" +
	"\n" +
	"pids_limit\x18> \x01(\x04R\tpidsLimit\x12!\n" +
	"\fipv4_address\x18G \x01(\tR\vipv4Address\x12!\n" +
	"\fipv6_address\x18H \x01(\tR\vipv6Address\x12\x1a\n" +
	"\bhostname\x18I \x01(\tR\bhostname\x12+\n" +
	"\x11inflight_requests\x18Q \x01(\x03R\x10inflightRequests\x12\x18\n" +
	"\ahealthy\x18[ \x01(\bR\ahealthy\x12!\n" +
	"\flast_updated\x18\\ \x01(\x03R\vlastUpdatedB.Z,github.com/agentuity/go-common/gravity/protob\x06proto3"

var (
	file_gravity_metrics_proto_rawDescOnce sync.Once
	file_gravity_metrics_proto_rawDescData []byte
)

func file_gravity_metrics_proto_rawDescGZIP() []byte {
	file_gravity_metrics_proto_rawDescOnce.Do(func() {
		file_gravity_metrics_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_gravity_metrics_proto_rawDesc), len(file_gravity_metrics_proto_rawDesc)))
	})
	return file_gravity_metrics_proto_rawDescData
}

var file_gravity_metrics_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_gravity_metrics_proto_goTypes = []any{
	(*ServerMetrics)(nil),         // 0: gravity.ServerMetrics
	(*GRPCConnectionMetrics)(nil), // 1: gravity.GRPCConnectionMetrics
	(*PerformanceMetrics)(nil),    // 2: gravity.PerformanceMetrics
	(*MessageStatistics)(nil),     // 3: gravity.MessageStatistics
	(*SystemResourceMetrics)(nil), // 4: gravity.SystemResourceMetrics
	(*HistoricalMetrics)(nil),     // 5: gravity.HistoricalMetrics
	(*ThroughputSample)(nil),      // 6: gravity.ThroughputSample
	(*LatencySample)(nil),         // 7: gravity.LatencySample
	(*ErrorRateSample)(nil),       // 8: gravity.ErrorRateSample
	(*HealthSample)(nil),          // 9: gravity.HealthSample
	(*ProjectRuntimeStats)(nil),   // 10: gravity.ProjectRuntimeStats
	nil,                           // 11: gravity.PerformanceMetrics.RuntimeStatsEntry
	nil,                           // 12: gravity.MessageStatistics.MessagesByTypeEntry
}
var file_gravity_metrics_proto_depIdxs = []int32{
	1,  // 0: gravity.ServerMetrics.grpc_metrics:type_name -> gravity.GRPCConnectionMetrics
	2,  // 1: gravity.ServerMetrics.performance:type_name -> gravity.PerformanceMetrics
	3,  // 2: gravity.ServerMetrics.message_stats:type_name -> gravity.MessageStatistics
	4,  // 3: gravity.ServerMetrics.system_metrics:type_name -> gravity.SystemResourceMetrics
	5,  // 4: gravity.ServerMetrics.historical_data:type_name -> gravity.HistoricalMetrics
	11, // 5: gravity.PerformanceMetrics.runtime_stats:type_name -> gravity.PerformanceMetrics.RuntimeStatsEntry
	12, // 6: gravity.MessageStatistics.messages_by_type:type_name -> gravity.MessageStatistics.MessagesByTypeEntry
	6,  // 7: gravity.HistoricalMetrics.throughput_history:type_name -> gravity.ThroughputSample
	7,  // 8: gravity.HistoricalMetrics.latency_history:type_name -> gravity.LatencySample
	8,  // 9: gravity.HistoricalMetrics.error_rate_history:type_name -> gravity.ErrorRateSample
	9,  // 10: gravity.HistoricalMetrics.health_history:type_name -> gravity.HealthSample
	10, // 11: gravity.PerformanceMetrics.RuntimeStatsEntry.value:type_name -> gravity.ProjectRuntimeStats
	12, // [12:12] is the sub-list for method output_type
	12, // [12:12] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_gravity_metrics_proto_init() }
func file_gravity_metrics_proto_init() {
	if File_gravity_metrics_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gravity_metrics_proto_rawDesc), len(file_gravity_metrics_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_gravity_metrics_proto_goTypes,
		DependencyIndexes: file_gravity_metrics_proto_depIdxs,
		MessageInfos:      file_gravity_metrics_proto_msgTypes,
	}.Build()
	File_gravity_metrics_proto = out.File
	file_gravity_metrics_proto_goTypes = nil
	file_gravity_metrics_proto_depIdxs = nil
}
