// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: gravity_session.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// IdentifyRequest is sent by the client to identify the org associated with the key.
type IdentifyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InstanceId    string                 `protobuf:"bytes,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"` // Instance ID (must match cert CN)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IdentifyRequest) Reset() {
	*x = IdentifyRequest{}
	mi := &file_gravity_session_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IdentifyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdentifyRequest) ProtoMessage() {}

func (x *IdentifyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gravity_session_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdentifyRequest.ProtoReflect.Descriptor instead.
func (*IdentifyRequest) Descriptor() ([]byte, []int) {
	return file_gravity_session_proto_rawDescGZIP(), []int{0}
}

func (x *IdentifyRequest) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

// IdentifyResponse contains the org ID from cert verification.
type IdentifyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrgId         string                 `protobuf:"bytes,1,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"` // Organization ID (from cert verification)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IdentifyResponse) Reset() {
	*x = IdentifyResponse{}
	mi := &file_gravity_session_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IdentifyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdentifyResponse) ProtoMessage() {}

func (x *IdentifyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gravity_session_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdentifyResponse.ProtoReflect.Descriptor instead.
func (*IdentifyResponse) Descriptor() ([]byte, []int) {
	return file_gravity_session_proto_rawDescGZIP(), []int{1}
}

func (x *IdentifyResponse) GetOrgId() string {
	if x != nil {
		return x.OrgId
	}
	return ""
}

// SessionMessage is the bidirectional message type for EstablishSession.
// It contains all control plane messages for the session lifecycle.
type SessionMessage struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Id       string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	StreamId string                 `protobuf:"bytes,2,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"` // Logical stream identifier for multiplexing
	// Types that are valid to be assigned to MessageType:
	//
	//	*SessionMessage_SessionHello
	//	*SessionMessage_SessionHelloResponse
	//	*SessionMessage_SessionClose
	//	*SessionMessage_RouteDeployment
	//	*SessionMessage_RouteDeploymentResponse
	//	*SessionMessage_Unprovision
	//	*SessionMessage_RouteSandbox
	//	*SessionMessage_RouteSandboxResponse
	//	*SessionMessage_Ping
	//	*SessionMessage_Pong
	//	*SessionMessage_Report
	//	*SessionMessage_Pause
	//	*SessionMessage_Resume
	//	*SessionMessage_ConfigUpdate
	//	*SessionMessage_ConfigUpdateResponse
	//	*SessionMessage_Response
	//	*SessionMessage_Event
	MessageType   isSessionMessage_MessageType `protobuf_oneof:"message_type"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionMessage) Reset() {
	*x = SessionMessage{}
	mi := &file_gravity_session_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionMessage) ProtoMessage() {}

func (x *SessionMessage) ProtoReflect() protoreflect.Message {
	mi := &file_gravity_session_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionMessage.ProtoReflect.Descriptor instead.
func (*SessionMessage) Descriptor() ([]byte, []int) {
	return file_gravity_session_proto_rawDescGZIP(), []int{2}
}

func (x *SessionMessage) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SessionMessage) GetStreamId() string {
	if x != nil {
		return x.StreamId
	}
	return ""
}

func (x *SessionMessage) GetMessageType() isSessionMessage_MessageType {
	if x != nil {
		return x.MessageType
	}
	return nil
}

func (x *SessionMessage) GetSessionHello() *SessionHello {
	if x != nil {
		if x, ok := x.MessageType.(*SessionMessage_SessionHello); ok {
			return x.SessionHello
		}
	}
	return nil
}

func (x *SessionMessage) GetSessionHelloResponse() *SessionHelloResponse {
	if x != nil {
		if x, ok := x.MessageType.(*SessionMessage_SessionHelloResponse); ok {
			return x.SessionHelloResponse
		}
	}
	return nil
}

func (x *SessionMessage) GetSessionClose() *SessionCloseRequest {
	if x != nil {
		if x, ok := x.MessageType.(*SessionMessage_SessionClose); ok {
			return x.SessionClose
		}
	}
	return nil
}

func (x *SessionMessage) GetRouteDeployment() *RouteDeploymentRequest {
	if x != nil {
		if x, ok := x.MessageType.(*SessionMessage_RouteDeployment); ok {
			return x.RouteDeployment
		}
	}
	return nil
}

func (x *SessionMessage) GetRouteDeploymentResponse() *RouteDeploymentResponse {
	if x != nil {
		if x, ok := x.MessageType.(*SessionMessage_RouteDeploymentResponse); ok {
			return x.RouteDeploymentResponse
		}
	}
	return nil
}

func (x *SessionMessage) GetUnprovision() *UnprovisionRequest {
	if x != nil {
		if x, ok := x.MessageType.(*SessionMessage_Unprovision); ok {
			return x.Unprovision
		}
	}
	return nil
}

func (x *SessionMessage) GetRouteSandbox() *RouteSandboxRequest {
	if x != nil {
		if x, ok := x.MessageType.(*SessionMessage_RouteSandbox); ok {
			return x.RouteSandbox
		}
	}
	return nil
}

func (x *SessionMessage) GetRouteSandboxResponse() *RouteSandboxResponse {
	if x != nil {
		if x, ok := x.MessageType.(*SessionMessage_RouteSandboxResponse); ok {
			return x.RouteSandboxResponse
		}
	}
	return nil
}

func (x *SessionMessage) GetPing() *PingRequest {
	if x != nil {
		if x, ok := x.MessageType.(*SessionMessage_Ping); ok {
			return x.Ping
		}
	}
	return nil
}

func (x *SessionMessage) GetPong() *PongResponse {
	if x != nil {
		if x, ok := x.MessageType.(*SessionMessage_Pong); ok {
			return x.Pong
		}
	}
	return nil
}

func (x *SessionMessage) GetReport() *ReportRequest {
	if x != nil {
		if x, ok := x.MessageType.(*SessionMessage_Report); ok {
			return x.Report
		}
	}
	return nil
}

func (x *SessionMessage) GetPause() *PauseRequest {
	if x != nil {
		if x, ok := x.MessageType.(*SessionMessage_Pause); ok {
			return x.Pause
		}
	}
	return nil
}

func (x *SessionMessage) GetResume() *ResumeRequest {
	if x != nil {
		if x, ok := x.MessageType.(*SessionMessage_Resume); ok {
			return x.Resume
		}
	}
	return nil
}

func (x *SessionMessage) GetConfigUpdate() *ConfigurationUpdate {
	if x != nil {
		if x, ok := x.MessageType.(*SessionMessage_ConfigUpdate); ok {
			return x.ConfigUpdate
		}
	}
	return nil
}

func (x *SessionMessage) GetConfigUpdateResponse() *ConfigurationUpdateResponse {
	if x != nil {
		if x, ok := x.MessageType.(*SessionMessage_ConfigUpdateResponse); ok {
			return x.ConfigUpdateResponse
		}
	}
	return nil
}

func (x *SessionMessage) GetResponse() *ProtocolResponse {
	if x != nil {
		if x, ok := x.MessageType.(*SessionMessage_Response); ok {
			return x.Response
		}
	}
	return nil
}

func (x *SessionMessage) GetEvent() *ProtocolEvent {
	if x != nil {
		if x, ok := x.MessageType.(*SessionMessage_Event); ok {
			return x.Event
		}
	}
	return nil
}

type isSessionMessage_MessageType interface {
	isSessionMessage_MessageType()
}

type SessionMessage_SessionHello struct {
	// Session lifecycle (10-19)
	SessionHello *SessionHello `protobuf:"bytes,10,opt,name=session_hello,json=sessionHello,proto3,oneof"`
}

type SessionMessage_SessionHelloResponse struct {
	SessionHelloResponse *SessionHelloResponse `protobuf:"bytes,11,opt,name=session_hello_response,json=sessionHelloResponse,proto3,oneof"`
}

type SessionMessage_SessionClose struct {
	SessionClose *SessionCloseRequest `protobuf:"bytes,15,opt,name=session_close,json=sessionClose,proto3,oneof"`
}

type SessionMessage_RouteDeployment struct {
	// Deployment management (20-29)
	RouteDeployment *RouteDeploymentRequest `protobuf:"bytes,22,opt,name=route_deployment,json=routeDeployment,proto3,oneof"`
}

type SessionMessage_RouteDeploymentResponse struct {
	RouteDeploymentResponse *RouteDeploymentResponse `protobuf:"bytes,23,opt,name=route_deployment_response,json=routeDeploymentResponse,proto3,oneof"`
}

type SessionMessage_Unprovision struct {
	Unprovision *UnprovisionRequest `protobuf:"bytes,25,opt,name=unprovision,proto3,oneof"`
}

type SessionMessage_RouteSandbox struct {
	RouteSandbox *RouteSandboxRequest `protobuf:"bytes,26,opt,name=route_sandbox,json=routeSandbox,proto3,oneof"`
}

type SessionMessage_RouteSandboxResponse struct {
	RouteSandboxResponse *RouteSandboxResponse `protobuf:"bytes,27,opt,name=route_sandbox_response,json=routeSandboxResponse,proto3,oneof"`
}

type SessionMessage_Ping struct {
	// Health and monitoring (30-39)
	Ping *PingRequest `protobuf:"bytes,30,opt,name=ping,proto3,oneof"`
}

type SessionMessage_Pong struct {
	Pong *PongResponse `protobuf:"bytes,31,opt,name=pong,proto3,oneof"`
}

type SessionMessage_Report struct {
	Report *ReportRequest `protobuf:"bytes,32,opt,name=report,proto3,oneof"`
}

type SessionMessage_Pause struct {
	// Session control (40-49)
	Pause *PauseRequest `protobuf:"bytes,40,opt,name=pause,proto3,oneof"`
}

type SessionMessage_Resume struct {
	Resume *ResumeRequest `protobuf:"bytes,41,opt,name=resume,proto3,oneof"`
}

type SessionMessage_ConfigUpdate struct {
	// Configuration management (45-49)
	ConfigUpdate *ConfigurationUpdate `protobuf:"bytes,45,opt,name=config_update,json=configUpdate,proto3,oneof"`
}

type SessionMessage_ConfigUpdateResponse struct {
	ConfigUpdateResponse *ConfigurationUpdateResponse `protobuf:"bytes,46,opt,name=config_update_response,json=configUpdateResponse,proto3,oneof"`
}

type SessionMessage_Response struct {
	// Generic protocol messages (50-59)
	Response *ProtocolResponse `protobuf:"bytes,50,opt,name=response,proto3,oneof"`
}

type SessionMessage_Event struct {
	Event *ProtocolEvent `protobuf:"bytes,51,opt,name=event,proto3,oneof"`
}

func (*SessionMessage_SessionHello) isSessionMessage_MessageType() {}

func (*SessionMessage_SessionHelloResponse) isSessionMessage_MessageType() {}

func (*SessionMessage_SessionClose) isSessionMessage_MessageType() {}

func (*SessionMessage_RouteDeployment) isSessionMessage_MessageType() {}

func (*SessionMessage_RouteDeploymentResponse) isSessionMessage_MessageType() {}

func (*SessionMessage_Unprovision) isSessionMessage_MessageType() {}

func (*SessionMessage_RouteSandbox) isSessionMessage_MessageType() {}

func (*SessionMessage_RouteSandboxResponse) isSessionMessage_MessageType() {}

func (*SessionMessage_Ping) isSessionMessage_MessageType() {}

func (*SessionMessage_Pong) isSessionMessage_MessageType() {}

func (*SessionMessage_Report) isSessionMessage_MessageType() {}

func (*SessionMessage_Pause) isSessionMessage_MessageType() {}

func (*SessionMessage_Resume) isSessionMessage_MessageType() {}

func (*SessionMessage_ConfigUpdate) isSessionMessage_MessageType() {}

func (*SessionMessage_ConfigUpdateResponse) isSessionMessage_MessageType() {}

func (*SessionMessage_Response) isSessionMessage_MessageType() {}

func (*SessionMessage_Event) isSessionMessage_MessageType() {}

// SessionHello is sent by the client as the first message after TLS handshake.
// The org_id and instance_id are extracted from the client certificate.
type SessionHello struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ProtocolVersion int32                  `protobuf:"varint,1,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"` // Protocol version number for compatibility
	ClientVersion   string                 `protobuf:"bytes,2,opt,name=client_version,json=clientVersion,proto3" json:"client_version,omitempty"`        // Version string of the client (e.g., SHA, semver)
	ClientName      string                 `protobuf:"bytes,3,opt,name=client_name,json=clientName,proto3" json:"client_name,omitempty"`                 // Name of the client application (e.g., "hadron")
	Deployments     []*ExistingDeployment  `protobuf:"bytes,4,rep,name=deployments,proto3" json:"deployments,omitempty"`                                 // List of existing deployments to restore
	HostInfo        *HostInfo              `protobuf:"bytes,5,opt,name=host_info,json=hostInfo,proto3" json:"host_info,omitempty"`                       // Information about the host system
	Capabilities    *ClientCapabilities    `protobuf:"bytes,6,opt,name=capabilities,proto3" json:"capabilities,omitempty"`                               // Client capabilities for this session
	// Instance metadata (extracted from cert but also sent for validation)
	InstanceId string `protobuf:"bytes,7,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"` // Instance ID (must match cert CN)
	// Provider information
	Provider      string   `protobuf:"bytes,8,opt,name=provider,proto3" json:"provider,omitempty"`                              // Cloud provider (e.g., "aws", "gcp", "azure")
	Region        string   `protobuf:"bytes,9,opt,name=region,proto3" json:"region,omitempty"`                                  // Cloud region
	InstanceType  string   `protobuf:"bytes,10,opt,name=instance_type,json=instanceType,proto3" json:"instance_type,omitempty"` // instance type of the client (n1-standard-32, m6i.8xlarge)
	InstanceTags  []string `protobuf:"bytes,11,rep,name=instance_tags,json=instanceTags,proto3" json:"instance_tags,omitempty"` // tags on the instance
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionHello) Reset() {
	*x = SessionHello{}
	mi := &file_gravity_session_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionHello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionHello) ProtoMessage() {}

func (x *SessionHello) ProtoReflect() protoreflect.Message {
	mi := &file_gravity_session_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionHello.ProtoReflect.Descriptor instead.
func (*SessionHello) Descriptor() ([]byte, []int) {
	return file_gravity_session_proto_rawDescGZIP(), []int{3}
}

func (x *SessionHello) GetProtocolVersion() int32 {
	if x != nil {
		return x.ProtocolVersion
	}
	return 0
}

func (x *SessionHello) GetClientVersion() string {
	if x != nil {
		return x.ClientVersion
	}
	return ""
}

func (x *SessionHello) GetClientName() string {
	if x != nil {
		return x.ClientName
	}
	return ""
}

func (x *SessionHello) GetDeployments() []*ExistingDeployment {
	if x != nil {
		return x.Deployments
	}
	return nil
}

func (x *SessionHello) GetHostInfo() *HostInfo {
	if x != nil {
		return x.HostInfo
	}
	return nil
}

func (x *SessionHello) GetCapabilities() *ClientCapabilities {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *SessionHello) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *SessionHello) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *SessionHello) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *SessionHello) GetInstanceType() string {
	if x != nil {
		return x.InstanceType
	}
	return ""
}

func (x *SessionHello) GetInstanceTags() []string {
	if x != nil {
		return x.InstanceTags
	}
	return nil
}

// SessionHelloResponse is sent by the server after successful authentication.
type SessionHelloResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	MachineId         string                 `protobuf:"bytes,1,opt,name=machine_id,json=machineId,proto3" json:"machine_id,omitempty"`                            // Deterministic machine ID assigned by server
	OrgId             string                 `protobuf:"bytes,2,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`                                        // Organization ID (from cert verification)
	OtlpUrl           string                 `protobuf:"bytes,3,opt,name=otlp_url,json=otlpUrl,proto3" json:"otlp_url,omitempty"`                                  // OpenTelemetry endpoint URL for metrics
	OtlpKey           string                 `protobuf:"bytes,4,opt,name=otlp_key,json=otlpKey,proto3" json:"otlp_key,omitempty"`                                  // OpenTelemetry API key for authentication
	ApiUrl            string                 `protobuf:"bytes,5,opt,name=api_url,json=apiUrl,proto3" json:"api_url,omitempty"`                                     // Base URL for API operations
	Environment       []string               `protobuf:"bytes,6,rep,name=environment,proto3" json:"environment,omitempty"`                                         // Environment variables to set
	HostMapping       []*HostMapping         `protobuf:"bytes,7,rep,name=host_mapping,json=hostMapping,proto3" json:"host_mapping,omitempty"`                      // Host to IP address mappings
	SubnetRoutes      []string               `protobuf:"bytes,8,rep,name=subnet_routes,json=subnetRoutes,proto3" json:"subnet_routes,omitempty"`                   // Subnet routes for the session
	GravityServer     string                 `protobuf:"bytes,9,opt,name=gravity_server,json=gravityServer,proto3" json:"gravity_server,omitempty"`                // The gravity server that we're connected to
	Hostname          string                 `protobuf:"bytes,10,opt,name=hostname,proto3" json:"hostname,omitempty"`                                              // Dynamic hostname if requested
	SshPublicKey      []byte                 `protobuf:"bytes,11,opt,name=ssh_public_key,json=sshPublicKey,proto3" json:"ssh_public_key,omitempty"`                // SSH public key for internal trusted connections
	MachineToken      string                 `protobuf:"bytes,12,opt,name=machine_token,json=machineToken,proto3" json:"machine_token,omitempty"`                  // JWT token for machine to authenticate with catalyst
	MachineCertBundle string                 `protobuf:"bytes,13,opt,name=machine_cert_bundle,json=machineCertBundle,proto3" json:"machine_cert_bundle,omitempty"` // PEM certificate bundle (cert, ca, key)
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *SessionHelloResponse) Reset() {
	*x = SessionHelloResponse{}
	mi := &file_gravity_session_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionHelloResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionHelloResponse) ProtoMessage() {}

func (x *SessionHelloResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gravity_session_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionHelloResponse.ProtoReflect.Descriptor instead.
func (*SessionHelloResponse) Descriptor() ([]byte, []int) {
	return file_gravity_session_proto_rawDescGZIP(), []int{4}
}

func (x *SessionHelloResponse) GetMachineId() string {
	if x != nil {
		return x.MachineId
	}
	return ""
}

func (x *SessionHelloResponse) GetOrgId() string {
	if x != nil {
		return x.OrgId
	}
	return ""
}

func (x *SessionHelloResponse) GetOtlpUrl() string {
	if x != nil {
		return x.OtlpUrl
	}
	return ""
}

func (x *SessionHelloResponse) GetOtlpKey() string {
	if x != nil {
		return x.OtlpKey
	}
	return ""
}

func (x *SessionHelloResponse) GetApiUrl() string {
	if x != nil {
		return x.ApiUrl
	}
	return ""
}

func (x *SessionHelloResponse) GetEnvironment() []string {
	if x != nil {
		return x.Environment
	}
	return nil
}

func (x *SessionHelloResponse) GetHostMapping() []*HostMapping {
	if x != nil {
		return x.HostMapping
	}
	return nil
}

func (x *SessionHelloResponse) GetSubnetRoutes() []string {
	if x != nil {
		return x.SubnetRoutes
	}
	return nil
}

func (x *SessionHelloResponse) GetGravityServer() string {
	if x != nil {
		return x.GravityServer
	}
	return ""
}

func (x *SessionHelloResponse) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *SessionHelloResponse) GetSshPublicKey() []byte {
	if x != nil {
		return x.SshPublicKey
	}
	return nil
}

func (x *SessionHelloResponse) GetMachineToken() string {
	if x != nil {
		return x.MachineToken
	}
	return ""
}

func (x *SessionHelloResponse) GetMachineCertBundle() string {
	if x != nil {
		return x.MachineCertBundle
	}
	return ""
}

// SessionCloseRequest is sent to gracefully close the session.
type SessionCloseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reason        string                 `protobuf:"bytes,1,opt,name=reason,proto3" json:"reason,omitempty"` // Reason for closing the session
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionCloseRequest) Reset() {
	*x = SessionCloseRequest{}
	mi := &file_gravity_session_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionCloseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionCloseRequest) ProtoMessage() {}

func (x *SessionCloseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gravity_session_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionCloseRequest.ProtoReflect.Descriptor instead.
func (*SessionCloseRequest) Descriptor() ([]byte, []int) {
	return file_gravity_session_proto_rawDescGZIP(), []int{5}
}

func (x *SessionCloseRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

var File_gravity_session_proto protoreflect.FileDescriptor

const file_gravity_session_proto_rawDesc = "" +
	"\n" +
	"\x15gravity_session.proto\x12\agravity\x1a\rgravity.proto\"2\n" +
	"\x0fIdentifyRequest\x12\x1f\n" +
	"\vinstance_id\x18\x01 \x01(\tR\n" +
	"instanceId\")\n" +
	"\x10IdentifyResponse\x12\x15\n" +
	"\x06org_id\x18\x01 \x01(\tR\x05orgId\"\xaa\t\n" +
	"\x0eSessionMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tstream_id\x18\x02 \x01(\tR\bstreamId\x12<\n" +
	"\rsession_hello\x18\n" +
	" \x01(\v2\x15.gravity.SessionHelloH\x00R\fsessionHello\x12U\n" +
	"\x16session_hello_response\x18\v \x01(\v2\x1d.gravity.SessionHelloResponseH\x00R\x14sessionHelloResponse\x12C\n" +
	"\rsession_close\x18\x0f \x01(\v2\x1c.gravity.SessionCloseRequestH\x00R\fsessionClose\x12L\n" +
	"\x10route_deployment\x18\x16 \x01(\v2\x1f.gravity.RouteDeploymentRequestH\x00R\x0frouteDeployment\x12^\n" +
	"\x19route_deployment_response\x18\x17 \x01(\v2 .gravity.RouteDeploymentResponseH\x00R\x17routeDeploymentResponse\x12?\n" +
	"\vunprovision\x18\x19 \x01(\v2\x1b.gravity.UnprovisionRequestH\x00R\vunprovision\x12C\n" +
	"\rroute_sandbox\x18\x1a \x01(\v2\x1c.gravity.RouteSandboxRequestH\x00R\frouteSandbox\x12U\n" +
	"\x16route_sandbox_response\x18\x1b \x01(\v2\x1d.gravity.RouteSandboxResponseH\x00R\x14routeSandboxResponse\x12*\n" +
	"\x04ping\x18\x1e \x01(\v2\x14.gravity.PingRequestH\x00R\x04ping\x12+\n" +
	"\x04pong\x18\x1f \x01(\v2\x15.gravity.PongResponseH\x00R\x04pong\x120\n" +
	"\x06report\x18  \x01(\v2\x16.gravity.ReportRequestH\x00R\x06report\x12-\n" +
	"\x05pause\x18( \x01(\v2\x15.gravity.PauseRequestH\x00R\x05pause\x120\n" +
	"\x06resume\x18) \x01(\v2\x16.gravity.ResumeRequestH\x00R\x06resume\x12C\n" +
	"\rconfig_update\x18- \x01(\v2\x1c.gravity.ConfigurationUpdateH\x00R\fconfigUpdate\x12\\\n" +
	"\x16config_update_response\x18. \x01(\v2$.gravity.ConfigurationUpdateResponseH\x00R\x14configUpdateResponse\x127\n" +
	"\bresponse\x182 \x01(\v2\x19.gravity.ProtocolResponseH\x00R\bresponse\x12.\n" +
	"\x05event\x183 \x01(\v2\x16.gravity.ProtocolEventH\x00R\x05eventB\x0e\n" +
	"\fmessage_type\"\xd0\x03\n" +
	"\fSessionHello\x12)\n" +
	"\x10protocol_version\x18\x01 \x01(\x05R\x0fprotocolVersion\x12%\n" +
	"\x0eclient_version\x18\x02 \x01(\tR\rclientVersion\x12\x1f\n" +
	"\vclient_name\x18\x03 \x01(\tR\n" +
	"clientName\x12=\n" +
	"\vdeployments\x18\x04 \x03(\v2\x1b.gravity.ExistingDeploymentR\vdeployments\x12.\n" +
	"\thost_info\x18\x05 \x01(\v2\x11.gravity.HostInfoR\bhostInfo\x12?\n" +
	"\fcapabilities\x18\x06 \x01(\v2\x1b.gravity.ClientCapabilitiesR\fcapabilities\x12\x1f\n" +
	"\vinstance_id\x18\a \x01(\tR\n" +
	"instanceId\x12\x1a\n" +
	"\bprovider\x18\b \x01(\tR\bprovider\x12\x16\n" +
	"\x06region\x18\t \x01(\tR\x06region\x12#\n" +
	"\rinstance_type\x18\n" +
	" \x01(\tR\finstanceType\x12#\n" +
	"\rinstance_tags\x18\v \x03(\tR\finstanceTags\"\xd9\x03\n" +
	"\x14SessionHelloResponse\x12\x1d\n" +
	"\n" +
	"machine_id\x18\x01 \x01(\tR\tmachineId\x12\x15\n" +
	"\x06org_id\x18\x02 \x01(\tR\x05orgId\x12\x19\n" +
	"\botlp_url\x18\x03 \x01(\tR\aotlpUrl\x12\x19\n" +
	"\botlp_key\x18\x04 \x01(\tR\aotlpKey\x12\x17\n" +
	"\aapi_url\x18\x05 \x01(\tR\x06apiUrl\x12 \n" +
	"\venvironment\x18\x06 \x03(\tR\venvironment\x127\n" +
	"\fhost_mapping\x18\a \x03(\v2\x14.gravity.HostMappingR\vhostMapping\x12#\n" +
	"\rsubnet_routes\x18\b \x03(\tR\fsubnetRoutes\x12%\n" +
	"\x0egravity_server\x18\t \x01(\tR\rgravityServer\x12\x1a\n" +
	"\bhostname\x18\n" +
	" \x01(\tR\bhostname\x12$\n" +
	"\x0essh_public_key\x18\v \x01(\fR\fsshPublicKey\x12#\n" +
	"\rmachine_token\x18\f \x01(\tR\fmachineToken\x12.\n" +
	"\x13machine_cert_bundle\x18\r \x01(\tR\x11machineCertBundle\"-\n" +
	"\x13SessionCloseRequest\x12\x16\n" +
	"\x06reason\x18\x01 \x01(\tR\x06reason2\xa7\x03\n" +
	"\x15GravitySessionService\x12H\n" +
	"\x10EstablishSession\x12\x17.gravity.SessionMessage\x1a\x17.gravity.SessionMessage(\x010\x01\x12H\n" +
	"\x14StreamSessionPackets\x12\x15.gravity.TunnelPacket\x1a\x15.gravity.TunnelPacket(\x010\x01\x12`\n" +
	"\x15GetDeploymentMetadata\x12\".gravity.DeploymentMetadataRequest\x1a#.gravity.DeploymentMetadataResponse\x12W\n" +
	"\x12GetSandboxMetadata\x12\x1f.gravity.SandboxMetadataRequest\x1a .gravity.SandboxMetadataResponse\x12?\n" +
	"\bIdentify\x12\x18.gravity.IdentifyRequest\x1a\x19.gravity.IdentifyResponseB.Z,github.com/agentuity/go-common/gravity/protob\x06proto3"

var (
	file_gravity_session_proto_rawDescOnce sync.Once
	file_gravity_session_proto_rawDescData []byte
)

func file_gravity_session_proto_rawDescGZIP() []byte {
	file_gravity_session_proto_rawDescOnce.Do(func() {
		file_gravity_session_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_gravity_session_proto_rawDesc), len(file_gravity_session_proto_rawDesc)))
	})
	return file_gravity_session_proto_rawDescData
}

var file_gravity_session_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_gravity_session_proto_goTypes = []any{
	(*IdentifyRequest)(nil),             // 0: gravity.IdentifyRequest
	(*IdentifyResponse)(nil),            // 1: gravity.IdentifyResponse
	(*SessionMessage)(nil),              // 2: gravity.SessionMessage
	(*SessionHello)(nil),                // 3: gravity.SessionHello
	(*SessionHelloResponse)(nil),        // 4: gravity.SessionHelloResponse
	(*SessionCloseRequest)(nil),         // 5: gravity.SessionCloseRequest
	(*RouteDeploymentRequest)(nil),      // 6: gravity.RouteDeploymentRequest
	(*RouteDeploymentResponse)(nil),     // 7: gravity.RouteDeploymentResponse
	(*UnprovisionRequest)(nil),          // 8: gravity.UnprovisionRequest
	(*RouteSandboxRequest)(nil),         // 9: gravity.RouteSandboxRequest
	(*RouteSandboxResponse)(nil),        // 10: gravity.RouteSandboxResponse
	(*PingRequest)(nil),                 // 11: gravity.PingRequest
	(*PongResponse)(nil),                // 12: gravity.PongResponse
	(*ReportRequest)(nil),               // 13: gravity.ReportRequest
	(*PauseRequest)(nil),                // 14: gravity.PauseRequest
	(*ResumeRequest)(nil),               // 15: gravity.ResumeRequest
	(*ConfigurationUpdate)(nil),         // 16: gravity.ConfigurationUpdate
	(*ConfigurationUpdateResponse)(nil), // 17: gravity.ConfigurationUpdateResponse
	(*ProtocolResponse)(nil),            // 18: gravity.ProtocolResponse
	(*ProtocolEvent)(nil),               // 19: gravity.ProtocolEvent
	(*ExistingDeployment)(nil),          // 20: gravity.ExistingDeployment
	(*HostInfo)(nil),                    // 21: gravity.HostInfo
	(*ClientCapabilities)(nil),          // 22: gravity.ClientCapabilities
	(*HostMapping)(nil),                 // 23: gravity.HostMapping
	(*TunnelPacket)(nil),                // 24: gravity.TunnelPacket
	(*DeploymentMetadataRequest)(nil),   // 25: gravity.DeploymentMetadataRequest
	(*SandboxMetadataRequest)(nil),      // 26: gravity.SandboxMetadataRequest
	(*DeploymentMetadataResponse)(nil),  // 27: gravity.DeploymentMetadataResponse
	(*SandboxMetadataResponse)(nil),     // 28: gravity.SandboxMetadataResponse
}
var file_gravity_session_proto_depIdxs = []int32{
	3,  // 0: gravity.SessionMessage.session_hello:type_name -> gravity.SessionHello
	4,  // 1: gravity.SessionMessage.session_hello_response:type_name -> gravity.SessionHelloResponse
	5,  // 2: gravity.SessionMessage.session_close:type_name -> gravity.SessionCloseRequest
	6,  // 3: gravity.SessionMessage.route_deployment:type_name -> gravity.RouteDeploymentRequest
	7,  // 4: gravity.SessionMessage.route_deployment_response:type_name -> gravity.RouteDeploymentResponse
	8,  // 5: gravity.SessionMessage.unprovision:type_name -> gravity.UnprovisionRequest
	9,  // 6: gravity.SessionMessage.route_sandbox:type_name -> gravity.RouteSandboxRequest
	10, // 7: gravity.SessionMessage.route_sandbox_response:type_name -> gravity.RouteSandboxResponse
	11, // 8: gravity.SessionMessage.ping:type_name -> gravity.PingRequest
	12, // 9: gravity.SessionMessage.pong:type_name -> gravity.PongResponse
	13, // 10: gravity.SessionMessage.report:type_name -> gravity.ReportRequest
	14, // 11: gravity.SessionMessage.pause:type_name -> gravity.PauseRequest
	15, // 12: gravity.SessionMessage.resume:type_name -> gravity.ResumeRequest
	16, // 13: gravity.SessionMessage.config_update:type_name -> gravity.ConfigurationUpdate
	17, // 14: gravity.SessionMessage.config_update_response:type_name -> gravity.ConfigurationUpdateResponse
	18, // 15: gravity.SessionMessage.response:type_name -> gravity.ProtocolResponse
	19, // 16: gravity.SessionMessage.event:type_name -> gravity.ProtocolEvent
	20, // 17: gravity.SessionHello.deployments:type_name -> gravity.ExistingDeployment
	21, // 18: gravity.SessionHello.host_info:type_name -> gravity.HostInfo
	22, // 19: gravity.SessionHello.capabilities:type_name -> gravity.ClientCapabilities
	23, // 20: gravity.SessionHelloResponse.host_mapping:type_name -> gravity.HostMapping
	2,  // 21: gravity.GravitySessionService.EstablishSession:input_type -> gravity.SessionMessage
	24, // 22: gravity.GravitySessionService.StreamSessionPackets:input_type -> gravity.TunnelPacket
	25, // 23: gravity.GravitySessionService.GetDeploymentMetadata:input_type -> gravity.DeploymentMetadataRequest
	26, // 24: gravity.GravitySessionService.GetSandboxMetadata:input_type -> gravity.SandboxMetadataRequest
	0,  // 25: gravity.GravitySessionService.Identify:input_type -> gravity.IdentifyRequest
	2,  // 26: gravity.GravitySessionService.EstablishSession:output_type -> gravity.SessionMessage
	24, // 27: gravity.GravitySessionService.StreamSessionPackets:output_type -> gravity.TunnelPacket
	27, // 28: gravity.GravitySessionService.GetDeploymentMetadata:output_type -> gravity.DeploymentMetadataResponse
	28, // 29: gravity.GravitySessionService.GetSandboxMetadata:output_type -> gravity.SandboxMetadataResponse
	1,  // 30: gravity.GravitySessionService.Identify:output_type -> gravity.IdentifyResponse
	26, // [26:31] is the sub-list for method output_type
	21, // [21:26] is the sub-list for method input_type
	21, // [21:21] is the sub-list for extension type_name
	21, // [21:21] is the sub-list for extension extendee
	0,  // [0:21] is the sub-list for field type_name
}

func init() { file_gravity_session_proto_init() }
func file_gravity_session_proto_init() {
	if File_gravity_session_proto != nil {
		return
	}
	file_gravity_proto_init()
	file_gravity_session_proto_msgTypes[2].OneofWrappers = []any{
		(*SessionMessage_SessionHello)(nil),
		(*SessionMessage_SessionHelloResponse)(nil),
		(*SessionMessage_SessionClose)(nil),
		(*SessionMessage_RouteDeployment)(nil),
		(*SessionMessage_RouteDeploymentResponse)(nil),
		(*SessionMessage_Unprovision)(nil),
		(*SessionMessage_RouteSandbox)(nil),
		(*SessionMessage_RouteSandboxResponse)(nil),
		(*SessionMessage_Ping)(nil),
		(*SessionMessage_Pong)(nil),
		(*SessionMessage_Report)(nil),
		(*SessionMessage_Pause)(nil),
		(*SessionMessage_Resume)(nil),
		(*SessionMessage_ConfigUpdate)(nil),
		(*SessionMessage_ConfigUpdateResponse)(nil),
		(*SessionMessage_Response)(nil),
		(*SessionMessage_Event)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gravity_session_proto_rawDesc), len(file_gravity_session_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_gravity_session_proto_goTypes,
		DependencyIndexes: file_gravity_session_proto_depIdxs,
		MessageInfos:      file_gravity_session_proto_msgTypes,
	}.Build()
	File_gravity_session_proto = out.File
	file_gravity_session_proto_goTypes = nil
	file_gravity_session_proto_depIdxs = nil
}
