// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: gravity_session.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GravitySessionService_EstablishSession_FullMethodName      = "/gravity.GravitySessionService/EstablishSession"
	GravitySessionService_StreamSessionPackets_FullMethodName  = "/gravity.GravitySessionService/StreamSessionPackets"
	GravitySessionService_GetDeploymentMetadata_FullMethodName = "/gravity.GravitySessionService/GetDeploymentMetadata"
	GravitySessionService_GetSandboxMetadata_FullMethodName    = "/gravity.GravitySessionService/GetSandboxMetadata"
	GravitySessionService_Identify_FullMethodName              = "/gravity.GravitySessionService/Identify"
)

// GravitySessionServiceClient is the client API for GravitySessionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// GravitySessionService handles session establishment and tunnel management
// using self-signed client certificates authenticated against the org's
// registered public key.
//
// This service replaces the legacy Provision + EstablishTunnelg two-step flow
// with a single-step session establishment.
type GravitySessionServiceClient interface {
	// EstablishSession creates a bidirectional control stream.
	// Authentication is performed via mTLS using self-signed client certificates.
	// The client's certificate public key is verified against the org's registered key.
	EstablishSession(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[SessionMessage, SessionMessage], error)
	// StreamSessionPackets handles bidirectional packet data streaming.
	// Same as the legacy GravityTunnel.StreamPackets but on the new service.
	StreamSessionPackets(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[TunnelPacket, TunnelPacket], error)
	// GetDeploymentMetadata retrieves metadata for a deployment.
	GetDeploymentMetadata(ctx context.Context, in *DeploymentMetadataRequest, opts ...grpc.CallOption) (*DeploymentMetadataResponse, error)
	// GetSandboxMetadata retrieves metadata for a sandbox.
	GetSandboxMetadata(ctx context.Context, in *SandboxMetadataRequest, opts ...grpc.CallOption) (*SandboxMetadataResponse, error)
	// Identify performs a one-shot authentication to retrieve the org ID.
	// Authentication is performed via mTLS using self-signed client certificates.
	Identify(ctx context.Context, in *IdentifyRequest, opts ...grpc.CallOption) (*IdentifyResponse, error)
}

type gravitySessionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGravitySessionServiceClient(cc grpc.ClientConnInterface) GravitySessionServiceClient {
	return &gravitySessionServiceClient{cc}
}

func (c *gravitySessionServiceClient) EstablishSession(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[SessionMessage, SessionMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &GravitySessionService_ServiceDesc.Streams[0], GravitySessionService_EstablishSession_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SessionMessage, SessionMessage]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GravitySessionService_EstablishSessionClient = grpc.BidiStreamingClient[SessionMessage, SessionMessage]

func (c *gravitySessionServiceClient) StreamSessionPackets(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[TunnelPacket, TunnelPacket], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &GravitySessionService_ServiceDesc.Streams[1], GravitySessionService_StreamSessionPackets_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[TunnelPacket, TunnelPacket]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GravitySessionService_StreamSessionPacketsClient = grpc.BidiStreamingClient[TunnelPacket, TunnelPacket]

func (c *gravitySessionServiceClient) GetDeploymentMetadata(ctx context.Context, in *DeploymentMetadataRequest, opts ...grpc.CallOption) (*DeploymentMetadataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeploymentMetadataResponse)
	err := c.cc.Invoke(ctx, GravitySessionService_GetDeploymentMetadata_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gravitySessionServiceClient) GetSandboxMetadata(ctx context.Context, in *SandboxMetadataRequest, opts ...grpc.CallOption) (*SandboxMetadataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SandboxMetadataResponse)
	err := c.cc.Invoke(ctx, GravitySessionService_GetSandboxMetadata_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gravitySessionServiceClient) Identify(ctx context.Context, in *IdentifyRequest, opts ...grpc.CallOption) (*IdentifyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IdentifyResponse)
	err := c.cc.Invoke(ctx, GravitySessionService_Identify_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GravitySessionServiceServer is the server API for GravitySessionService service.
// All implementations must embed UnimplementedGravitySessionServiceServer
// for forward compatibility.
//
// GravitySessionService handles session establishment and tunnel management
// using self-signed client certificates authenticated against the org's
// registered public key.
//
// This service replaces the legacy Provision + EstablishTunnelg two-step flow
// with a single-step session establishment.
type GravitySessionServiceServer interface {
	// EstablishSession creates a bidirectional control stream.
	// Authentication is performed via mTLS using self-signed client certificates.
	// The client's certificate public key is verified against the org's registered key.
	EstablishSession(grpc.BidiStreamingServer[SessionMessage, SessionMessage]) error
	// StreamSessionPackets handles bidirectional packet data streaming.
	// Same as the legacy GravityTunnel.StreamPackets but on the new service.
	StreamSessionPackets(grpc.BidiStreamingServer[TunnelPacket, TunnelPacket]) error
	// GetDeploymentMetadata retrieves metadata for a deployment.
	GetDeploymentMetadata(context.Context, *DeploymentMetadataRequest) (*DeploymentMetadataResponse, error)
	// GetSandboxMetadata retrieves metadata for a sandbox.
	GetSandboxMetadata(context.Context, *SandboxMetadataRequest) (*SandboxMetadataResponse, error)
	// Identify performs a one-shot authentication to retrieve the org ID.
	// Authentication is performed via mTLS using self-signed client certificates.
	Identify(context.Context, *IdentifyRequest) (*IdentifyResponse, error)
	mustEmbedUnimplementedGravitySessionServiceServer()
}

// UnimplementedGravitySessionServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGravitySessionServiceServer struct{}

func (UnimplementedGravitySessionServiceServer) EstablishSession(grpc.BidiStreamingServer[SessionMessage, SessionMessage]) error {
	return status.Errorf(codes.Unimplemented, "method EstablishSession not implemented")
}
func (UnimplementedGravitySessionServiceServer) StreamSessionPackets(grpc.BidiStreamingServer[TunnelPacket, TunnelPacket]) error {
	return status.Errorf(codes.Unimplemented, "method StreamSessionPackets not implemented")
}
func (UnimplementedGravitySessionServiceServer) GetDeploymentMetadata(context.Context, *DeploymentMetadataRequest) (*DeploymentMetadataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDeploymentMetadata not implemented")
}
func (UnimplementedGravitySessionServiceServer) GetSandboxMetadata(context.Context, *SandboxMetadataRequest) (*SandboxMetadataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSandboxMetadata not implemented")
}
func (UnimplementedGravitySessionServiceServer) Identify(context.Context, *IdentifyRequest) (*IdentifyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Identify not implemented")
}
func (UnimplementedGravitySessionServiceServer) mustEmbedUnimplementedGravitySessionServiceServer() {}
func (UnimplementedGravitySessionServiceServer) testEmbeddedByValue()                               {}

// UnsafeGravitySessionServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GravitySessionServiceServer will
// result in compilation errors.
type UnsafeGravitySessionServiceServer interface {
	mustEmbedUnimplementedGravitySessionServiceServer()
}

func RegisterGravitySessionServiceServer(s grpc.ServiceRegistrar, srv GravitySessionServiceServer) {
	// If the following call pancis, it indicates UnimplementedGravitySessionServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GravitySessionService_ServiceDesc, srv)
}

func _GravitySessionService_EstablishSession_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(GravitySessionServiceServer).EstablishSession(&grpc.GenericServerStream[SessionMessage, SessionMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GravitySessionService_EstablishSessionServer = grpc.BidiStreamingServer[SessionMessage, SessionMessage]

func _GravitySessionService_StreamSessionPackets_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(GravitySessionServiceServer).StreamSessionPackets(&grpc.GenericServerStream[TunnelPacket, TunnelPacket]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GravitySessionService_StreamSessionPacketsServer = grpc.BidiStreamingServer[TunnelPacket, TunnelPacket]

func _GravitySessionService_GetDeploymentMetadata_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeploymentMetadataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GravitySessionServiceServer).GetDeploymentMetadata(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GravitySessionService_GetDeploymentMetadata_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GravitySessionServiceServer).GetDeploymentMetadata(ctx, req.(*DeploymentMetadataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GravitySessionService_GetSandboxMetadata_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SandboxMetadataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GravitySessionServiceServer).GetSandboxMetadata(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GravitySessionService_GetSandboxMetadata_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GravitySessionServiceServer).GetSandboxMetadata(ctx, req.(*SandboxMetadataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GravitySessionService_Identify_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IdentifyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GravitySessionServiceServer).Identify(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GravitySessionService_Identify_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GravitySessionServiceServer).Identify(ctx, req.(*IdentifyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GravitySessionService_ServiceDesc is the grpc.ServiceDesc for GravitySessionService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GravitySessionService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gravity.GravitySessionService",
	HandlerType: (*GravitySessionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetDeploymentMetadata",
			Handler:    _GravitySessionService_GetDeploymentMetadata_Handler,
		},
		{
			MethodName: "GetSandboxMetadata",
			Handler:    _GravitySessionService_GetSandboxMetadata_Handler,
		},
		{
			MethodName: "Identify",
			Handler:    _GravitySessionService_Identify_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "EstablishSession",
			Handler:       _GravitySessionService_EstablishSession_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "StreamSessionPackets",
			Handler:       _GravitySessionService_StreamSessionPackets_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "gravity_session.proto",
}
