// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: gravity_monitor.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NodeEventLevel int32

const (
	NodeEventLevel_NODE_EVENT_LEVEL_UNSPECIFIED NodeEventLevel = 0
	NodeEventLevel_NODE_EVENT_LEVEL_INFO        NodeEventLevel = 1
	NodeEventLevel_NODE_EVENT_LEVEL_WARN        NodeEventLevel = 2
	NodeEventLevel_NODE_EVENT_LEVEL_ERROR       NodeEventLevel = 3
	NodeEventLevel_NODE_EVENT_LEVEL_CRITICAL    NodeEventLevel = 4
)

// Enum value maps for NodeEventLevel.
var (
	NodeEventLevel_name = map[int32]string{
		0: "NODE_EVENT_LEVEL_UNSPECIFIED",
		1: "NODE_EVENT_LEVEL_INFO",
		2: "NODE_EVENT_LEVEL_WARN",
		3: "NODE_EVENT_LEVEL_ERROR",
		4: "NODE_EVENT_LEVEL_CRITICAL",
	}
	NodeEventLevel_value = map[string]int32{
		"NODE_EVENT_LEVEL_UNSPECIFIED": 0,
		"NODE_EVENT_LEVEL_INFO":        1,
		"NODE_EVENT_LEVEL_WARN":        2,
		"NODE_EVENT_LEVEL_ERROR":       3,
		"NODE_EVENT_LEVEL_CRITICAL":    4,
	}
)

func (x NodeEventLevel) Enum() *NodeEventLevel {
	p := new(NodeEventLevel)
	*p = x
	return p
}

func (x NodeEventLevel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NodeEventLevel) Descriptor() protoreflect.EnumDescriptor {
	return file_gravity_monitor_proto_enumTypes[0].Descriptor()
}

func (NodeEventLevel) Type() protoreflect.EnumType {
	return &file_gravity_monitor_proto_enumTypes[0]
}

func (x NodeEventLevel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NodeEventLevel.Descriptor instead.
func (NodeEventLevel) EnumDescriptor() ([]byte, []int) {
	return file_gravity_monitor_proto_rawDescGZIP(), []int{0}
}

type NodeEventType int32

const (
	NodeEventType_NODE_EVENT_TYPE_UNSPECIFIED             NodeEventType = 0
	NodeEventType_NODE_EVENT_TYPE_CONTAINER_START         NodeEventType = 1
	NodeEventType_NODE_EVENT_TYPE_CONTAINER_STOP          NodeEventType = 2
	NodeEventType_NODE_EVENT_TYPE_CONTAINER_OOM           NodeEventType = 3
	NodeEventType_NODE_EVENT_TYPE_CONTAINER_HEALTH_CHANGE NodeEventType = 4
	NodeEventType_NODE_EVENT_TYPE_PRESSURE_THRESHOLD      NodeEventType = 5
	NodeEventType_NODE_EVENT_TYPE_DISK_NEARLY_FULL        NodeEventType = 6
	NodeEventType_NODE_EVENT_TYPE_COLLECTOR_ERROR         NodeEventType = 7
	NodeEventType_NODE_EVENT_TYPE_PRESSURE_ALERT          NodeEventType = 8
	NodeEventType_NODE_EVENT_TYPE_HEALTH_ALERT            NodeEventType = 9
)

// Enum value maps for NodeEventType.
var (
	NodeEventType_name = map[int32]string{
		0: "NODE_EVENT_TYPE_UNSPECIFIED",
		1: "NODE_EVENT_TYPE_CONTAINER_START",
		2: "NODE_EVENT_TYPE_CONTAINER_STOP",
		3: "NODE_EVENT_TYPE_CONTAINER_OOM",
		4: "NODE_EVENT_TYPE_CONTAINER_HEALTH_CHANGE",
		5: "NODE_EVENT_TYPE_PRESSURE_THRESHOLD",
		6: "NODE_EVENT_TYPE_DISK_NEARLY_FULL",
		7: "NODE_EVENT_TYPE_COLLECTOR_ERROR",
		8: "NODE_EVENT_TYPE_PRESSURE_ALERT",
		9: "NODE_EVENT_TYPE_HEALTH_ALERT",
	}
	NodeEventType_value = map[string]int32{
		"NODE_EVENT_TYPE_UNSPECIFIED":             0,
		"NODE_EVENT_TYPE_CONTAINER_START":         1,
		"NODE_EVENT_TYPE_CONTAINER_STOP":          2,
		"NODE_EVENT_TYPE_CONTAINER_OOM":           3,
		"NODE_EVENT_TYPE_CONTAINER_HEALTH_CHANGE": 4,
		"NODE_EVENT_TYPE_PRESSURE_THRESHOLD":      5,
		"NODE_EVENT_TYPE_DISK_NEARLY_FULL":        6,
		"NODE_EVENT_TYPE_COLLECTOR_ERROR":         7,
		"NODE_EVENT_TYPE_PRESSURE_ALERT":          8,
		"NODE_EVENT_TYPE_HEALTH_ALERT":            9,
	}
)

func (x NodeEventType) Enum() *NodeEventType {
	p := new(NodeEventType)
	*p = x
	return p
}

func (x NodeEventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NodeEventType) Descriptor() protoreflect.EnumDescriptor {
	return file_gravity_monitor_proto_enumTypes[1].Descriptor()
}

func (NodeEventType) Type() protoreflect.EnumType {
	return &file_gravity_monitor_proto_enumTypes[1]
}

func (x NodeEventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NodeEventType.Descriptor instead.
func (NodeEventType) EnumDescriptor() ([]byte, []int) {
	return file_gravity_monitor_proto_rawDescGZIP(), []int{1}
}

type NodeMonitorReport struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	MachineId             string                 `protobuf:"bytes,1,opt,name=machine_id,json=machineId,proto3" json:"machine_id,omitempty"`
	ReportedAtUs          int64                  `protobuf:"varint,2,opt,name=reported_at_us,json=reportedAtUs,proto3" json:"reported_at_us,omitempty"`
	Seq                   uint64                 `protobuf:"varint,3,opt,name=seq,proto3" json:"seq,omitempty"`
	Host                  *HostMetrics           `protobuf:"bytes,4,opt,name=host,proto3" json:"host,omitempty"`
	Containers            []*ContainerMetrics    `protobuf:"bytes,5,rep,name=containers,proto3" json:"containers,omitempty"`
	Capacity              *CapacitySummary       `protobuf:"bytes,6,opt,name=capacity,proto3" json:"capacity,omitempty"`
	Events                []*NodeEvent           `protobuf:"bytes,7,rep,name=events,proto3" json:"events,omitempty"`
	ReportIntervalSeconds int32                  `protobuf:"varint,8,opt,name=report_interval_seconds,json=reportIntervalSeconds,proto3" json:"report_interval_seconds,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *NodeMonitorReport) Reset() {
	*x = NodeMonitorReport{}
	mi := &file_gravity_monitor_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeMonitorReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeMonitorReport) ProtoMessage() {}

func (x *NodeMonitorReport) ProtoReflect() protoreflect.Message {
	mi := &file_gravity_monitor_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeMonitorReport.ProtoReflect.Descriptor instead.
func (*NodeMonitorReport) Descriptor() ([]byte, []int) {
	return file_gravity_monitor_proto_rawDescGZIP(), []int{0}
}

func (x *NodeMonitorReport) GetMachineId() string {
	if x != nil {
		return x.MachineId
	}
	return ""
}

func (x *NodeMonitorReport) GetReportedAtUs() int64 {
	if x != nil {
		return x.ReportedAtUs
	}
	return 0
}

func (x *NodeMonitorReport) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *NodeMonitorReport) GetHost() *HostMetrics {
	if x != nil {
		return x.Host
	}
	return nil
}

func (x *NodeMonitorReport) GetContainers() []*ContainerMetrics {
	if x != nil {
		return x.Containers
	}
	return nil
}

func (x *NodeMonitorReport) GetCapacity() *CapacitySummary {
	if x != nil {
		return x.Capacity
	}
	return nil
}

func (x *NodeMonitorReport) GetEvents() []*NodeEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

func (x *NodeMonitorReport) GetReportIntervalSeconds() int32 {
	if x != nil {
		return x.ReportIntervalSeconds
	}
	return 0
}

type HostMetrics struct {
	state             protoimpl.MessageState     `protogen:"open.v1"`
	Cpu               *CpuMetrics                `protobuf:"bytes,1,opt,name=cpu,proto3" json:"cpu,omitempty"`
	Memory            *MemoryMetrics             `protobuf:"bytes,2,opt,name=memory,proto3" json:"memory,omitempty"`
	Disks             []*DiskMetrics             `protobuf:"bytes,3,rep,name=disks,proto3" json:"disks,omitempty"`
	NetworkInterfaces []*NetworkInterfaceMetrics `protobuf:"bytes,4,rep,name=network_interfaces,json=networkInterfaces,proto3" json:"network_interfaces,omitempty"`
	System            *SystemInfo                `protobuf:"bytes,5,opt,name=system,proto3" json:"system,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *HostMetrics) Reset() {
	*x = HostMetrics{}
	mi := &file_gravity_monitor_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HostMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostMetrics) ProtoMessage() {}

func (x *HostMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_gravity_monitor_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostMetrics.ProtoReflect.Descriptor instead.
func (*HostMetrics) Descriptor() ([]byte, []int) {
	return file_gravity_monitor_proto_rawDescGZIP(), []int{1}
}

func (x *HostMetrics) GetCpu() *CpuMetrics {
	if x != nil {
		return x.Cpu
	}
	return nil
}

func (x *HostMetrics) GetMemory() *MemoryMetrics {
	if x != nil {
		return x.Memory
	}
	return nil
}

func (x *HostMetrics) GetDisks() []*DiskMetrics {
	if x != nil {
		return x.Disks
	}
	return nil
}

func (x *HostMetrics) GetNetworkInterfaces() []*NetworkInterfaceMetrics {
	if x != nil {
		return x.NetworkInterfaces
	}
	return nil
}

func (x *HostMetrics) GetSystem() *SystemInfo {
	if x != nil {
		return x.System
	}
	return nil
}

type CpuMetrics struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	UsagePercent     float64                `protobuf:"fixed64,1,opt,name=usage_percent,json=usagePercent,proto3" json:"usage_percent,omitempty"`
	CoreUsagePercent []float64              `protobuf:"fixed64,2,rep,packed,name=core_usage_percent,json=coreUsagePercent,proto3" json:"core_usage_percent,omitempty"`
	LoadAvg_1        float64                `protobuf:"fixed64,3,opt,name=load_avg_1,json=loadAvg1,proto3" json:"load_avg_1,omitempty"`
	LoadAvg_5        float64                `protobuf:"fixed64,4,opt,name=load_avg_5,json=loadAvg5,proto3" json:"load_avg_5,omitempty"`
	LoadAvg_15       float64                `protobuf:"fixed64,5,opt,name=load_avg_15,json=loadAvg15,proto3" json:"load_avg_15,omitempty"`
	CoreCount        int32                  `protobuf:"varint,6,opt,name=core_count,json=coreCount,proto3" json:"core_count,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CpuMetrics) Reset() {
	*x = CpuMetrics{}
	mi := &file_gravity_monitor_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CpuMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CpuMetrics) ProtoMessage() {}

func (x *CpuMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_gravity_monitor_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CpuMetrics.ProtoReflect.Descriptor instead.
func (*CpuMetrics) Descriptor() ([]byte, []int) {
	return file_gravity_monitor_proto_rawDescGZIP(), []int{2}
}

func (x *CpuMetrics) GetUsagePercent() float64 {
	if x != nil {
		return x.UsagePercent
	}
	return 0
}

func (x *CpuMetrics) GetCoreUsagePercent() []float64 {
	if x != nil {
		return x.CoreUsagePercent
	}
	return nil
}

func (x *CpuMetrics) GetLoadAvg_1() float64 {
	if x != nil {
		return x.LoadAvg_1
	}
	return 0
}

func (x *CpuMetrics) GetLoadAvg_5() float64 {
	if x != nil {
		return x.LoadAvg_5
	}
	return 0
}

func (x *CpuMetrics) GetLoadAvg_15() float64 {
	if x != nil {
		return x.LoadAvg_15
	}
	return 0
}

func (x *CpuMetrics) GetCoreCount() int32 {
	if x != nil {
		return x.CoreCount
	}
	return 0
}

type MemoryMetrics struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TotalBytes     uint64                 `protobuf:"varint,1,opt,name=total_bytes,json=totalBytes,proto3" json:"total_bytes,omitempty"`
	UsedBytes      uint64                 `protobuf:"varint,2,opt,name=used_bytes,json=usedBytes,proto3" json:"used_bytes,omitempty"`
	AvailableBytes uint64                 `protobuf:"varint,3,opt,name=available_bytes,json=availableBytes,proto3" json:"available_bytes,omitempty"`
	CachedBytes    uint64                 `protobuf:"varint,4,opt,name=cached_bytes,json=cachedBytes,proto3" json:"cached_bytes,omitempty"`
	BuffersBytes   uint64                 `protobuf:"varint,5,opt,name=buffers_bytes,json=buffersBytes,proto3" json:"buffers_bytes,omitempty"`
	SwapTotalBytes uint64                 `protobuf:"varint,6,opt,name=swap_total_bytes,json=swapTotalBytes,proto3" json:"swap_total_bytes,omitempty"`
	SwapUsedBytes  uint64                 `protobuf:"varint,7,opt,name=swap_used_bytes,json=swapUsedBytes,proto3" json:"swap_used_bytes,omitempty"`
	UsagePercent   float64                `protobuf:"fixed64,8,opt,name=usage_percent,json=usagePercent,proto3" json:"usage_percent,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MemoryMetrics) Reset() {
	*x = MemoryMetrics{}
	mi := &file_gravity_monitor_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemoryMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemoryMetrics) ProtoMessage() {}

func (x *MemoryMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_gravity_monitor_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemoryMetrics.ProtoReflect.Descriptor instead.
func (*MemoryMetrics) Descriptor() ([]byte, []int) {
	return file_gravity_monitor_proto_rawDescGZIP(), []int{3}
}

func (x *MemoryMetrics) GetTotalBytes() uint64 {
	if x != nil {
		return x.TotalBytes
	}
	return 0
}

func (x *MemoryMetrics) GetUsedBytes() uint64 {
	if x != nil {
		return x.UsedBytes
	}
	return 0
}

func (x *MemoryMetrics) GetAvailableBytes() uint64 {
	if x != nil {
		return x.AvailableBytes
	}
	return 0
}

func (x *MemoryMetrics) GetCachedBytes() uint64 {
	if x != nil {
		return x.CachedBytes
	}
	return 0
}

func (x *MemoryMetrics) GetBuffersBytes() uint64 {
	if x != nil {
		return x.BuffersBytes
	}
	return 0
}

func (x *MemoryMetrics) GetSwapTotalBytes() uint64 {
	if x != nil {
		return x.SwapTotalBytes
	}
	return 0
}

func (x *MemoryMetrics) GetSwapUsedBytes() uint64 {
	if x != nil {
		return x.SwapUsedBytes
	}
	return 0
}

func (x *MemoryMetrics) GetUsagePercent() float64 {
	if x != nil {
		return x.UsagePercent
	}
	return 0
}

type DiskMetrics struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	MountPoint      string                 `protobuf:"bytes,1,opt,name=mount_point,json=mountPoint,proto3" json:"mount_point,omitempty"`
	Device          string                 `protobuf:"bytes,2,opt,name=device,proto3" json:"device,omitempty"`
	FsType          string                 `protobuf:"bytes,3,opt,name=fs_type,json=fsType,proto3" json:"fs_type,omitempty"`
	TotalBytes      uint64                 `protobuf:"varint,4,opt,name=total_bytes,json=totalBytes,proto3" json:"total_bytes,omitempty"`
	UsedBytes       uint64                 `protobuf:"varint,5,opt,name=used_bytes,json=usedBytes,proto3" json:"used_bytes,omitempty"`
	AvailableBytes  uint64                 `protobuf:"varint,6,opt,name=available_bytes,json=availableBytes,proto3" json:"available_bytes,omitempty"`
	UsagePercent    float64                `protobuf:"fixed64,7,opt,name=usage_percent,json=usagePercent,proto3" json:"usage_percent,omitempty"`
	InodesTotal     uint64                 `protobuf:"varint,8,opt,name=inodes_total,json=inodesTotal,proto3" json:"inodes_total,omitempty"`
	InodesUsed      uint64                 `protobuf:"varint,9,opt,name=inodes_used,json=inodesUsed,proto3" json:"inodes_used,omitempty"`
	ReadBytesDelta  uint64                 `protobuf:"varint,10,opt,name=read_bytes_delta,json=readBytesDelta,proto3" json:"read_bytes_delta,omitempty"`
	WriteBytesDelta uint64                 `protobuf:"varint,11,opt,name=write_bytes_delta,json=writeBytesDelta,proto3" json:"write_bytes_delta,omitempty"`
	ReadOpsDelta    uint64                 `protobuf:"varint,12,opt,name=read_ops_delta,json=readOpsDelta,proto3" json:"read_ops_delta,omitempty"`
	WriteOpsDelta   uint64                 `protobuf:"varint,13,opt,name=write_ops_delta,json=writeOpsDelta,proto3" json:"write_ops_delta,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *DiskMetrics) Reset() {
	*x = DiskMetrics{}
	mi := &file_gravity_monitor_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiskMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiskMetrics) ProtoMessage() {}

func (x *DiskMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_gravity_monitor_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiskMetrics.ProtoReflect.Descriptor instead.
func (*DiskMetrics) Descriptor() ([]byte, []int) {
	return file_gravity_monitor_proto_rawDescGZIP(), []int{4}
}

func (x *DiskMetrics) GetMountPoint() string {
	if x != nil {
		return x.MountPoint
	}
	return ""
}

func (x *DiskMetrics) GetDevice() string {
	if x != nil {
		return x.Device
	}
	return ""
}

func (x *DiskMetrics) GetFsType() string {
	if x != nil {
		return x.FsType
	}
	return ""
}

func (x *DiskMetrics) GetTotalBytes() uint64 {
	if x != nil {
		return x.TotalBytes
	}
	return 0
}

func (x *DiskMetrics) GetUsedBytes() uint64 {
	if x != nil {
		return x.UsedBytes
	}
	return 0
}

func (x *DiskMetrics) GetAvailableBytes() uint64 {
	if x != nil {
		return x.AvailableBytes
	}
	return 0
}

func (x *DiskMetrics) GetUsagePercent() float64 {
	if x != nil {
		return x.UsagePercent
	}
	return 0
}

func (x *DiskMetrics) GetInodesTotal() uint64 {
	if x != nil {
		return x.InodesTotal
	}
	return 0
}

func (x *DiskMetrics) GetInodesUsed() uint64 {
	if x != nil {
		return x.InodesUsed
	}
	return 0
}

func (x *DiskMetrics) GetReadBytesDelta() uint64 {
	if x != nil {
		return x.ReadBytesDelta
	}
	return 0
}

func (x *DiskMetrics) GetWriteBytesDelta() uint64 {
	if x != nil {
		return x.WriteBytesDelta
	}
	return 0
}

func (x *DiskMetrics) GetReadOpsDelta() uint64 {
	if x != nil {
		return x.ReadOpsDelta
	}
	return 0
}

func (x *DiskMetrics) GetWriteOpsDelta() uint64 {
	if x != nil {
		return x.WriteOpsDelta
	}
	return 0
}

type NetworkInterfaceMetrics struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Name           string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	RxBytesDelta   uint64                 `protobuf:"varint,2,opt,name=rx_bytes_delta,json=rxBytesDelta,proto3" json:"rx_bytes_delta,omitempty"`
	TxBytesDelta   uint64                 `protobuf:"varint,3,opt,name=tx_bytes_delta,json=txBytesDelta,proto3" json:"tx_bytes_delta,omitempty"`
	RxPacketsDelta uint64                 `protobuf:"varint,4,opt,name=rx_packets_delta,json=rxPacketsDelta,proto3" json:"rx_packets_delta,omitempty"`
	TxPacketsDelta uint64                 `protobuf:"varint,5,opt,name=tx_packets_delta,json=txPacketsDelta,proto3" json:"tx_packets_delta,omitempty"`
	RxErrorsDelta  uint64                 `protobuf:"varint,6,opt,name=rx_errors_delta,json=rxErrorsDelta,proto3" json:"rx_errors_delta,omitempty"`
	TxErrorsDelta  uint64                 `protobuf:"varint,7,opt,name=tx_errors_delta,json=txErrorsDelta,proto3" json:"tx_errors_delta,omitempty"`
	RxDropsDelta   uint64                 `protobuf:"varint,8,opt,name=rx_drops_delta,json=rxDropsDelta,proto3" json:"rx_drops_delta,omitempty"`
	TxDropsDelta   uint64                 `protobuf:"varint,9,opt,name=tx_drops_delta,json=txDropsDelta,proto3" json:"tx_drops_delta,omitempty"`
	LinkState      string                 `protobuf:"bytes,10,opt,name=link_state,json=linkState,proto3" json:"link_state,omitempty"`
	SpeedMbps      uint64                 `protobuf:"varint,11,opt,name=speed_mbps,json=speedMbps,proto3" json:"speed_mbps,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *NetworkInterfaceMetrics) Reset() {
	*x = NetworkInterfaceMetrics{}
	mi := &file_gravity_monitor_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkInterfaceMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkInterfaceMetrics) ProtoMessage() {}

func (x *NetworkInterfaceMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_gravity_monitor_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkInterfaceMetrics.ProtoReflect.Descriptor instead.
func (*NetworkInterfaceMetrics) Descriptor() ([]byte, []int) {
	return file_gravity_monitor_proto_rawDescGZIP(), []int{5}
}

func (x *NetworkInterfaceMetrics) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *NetworkInterfaceMetrics) GetRxBytesDelta() uint64 {
	if x != nil {
		return x.RxBytesDelta
	}
	return 0
}

func (x *NetworkInterfaceMetrics) GetTxBytesDelta() uint64 {
	if x != nil {
		return x.TxBytesDelta
	}
	return 0
}

func (x *NetworkInterfaceMetrics) GetRxPacketsDelta() uint64 {
	if x != nil {
		return x.RxPacketsDelta
	}
	return 0
}

func (x *NetworkInterfaceMetrics) GetTxPacketsDelta() uint64 {
	if x != nil {
		return x.TxPacketsDelta
	}
	return 0
}

func (x *NetworkInterfaceMetrics) GetRxErrorsDelta() uint64 {
	if x != nil {
		return x.RxErrorsDelta
	}
	return 0
}

func (x *NetworkInterfaceMetrics) GetTxErrorsDelta() uint64 {
	if x != nil {
		return x.TxErrorsDelta
	}
	return 0
}

func (x *NetworkInterfaceMetrics) GetRxDropsDelta() uint64 {
	if x != nil {
		return x.RxDropsDelta
	}
	return 0
}

func (x *NetworkInterfaceMetrics) GetTxDropsDelta() uint64 {
	if x != nil {
		return x.TxDropsDelta
	}
	return 0
}

func (x *NetworkInterfaceMetrics) GetLinkState() string {
	if x != nil {
		return x.LinkState
	}
	return ""
}

func (x *NetworkInterfaceMetrics) GetSpeedMbps() uint64 {
	if x != nil {
		return x.SpeedMbps
	}
	return 0
}

type SystemInfo struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Hostname         string                 `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	KernelVersion    string                 `protobuf:"bytes,2,opt,name=kernel_version,json=kernelVersion,proto3" json:"kernel_version,omitempty"`
	Os               string                 `protobuf:"bytes,3,opt,name=os,proto3" json:"os,omitempty"`
	Arch             string                 `protobuf:"bytes,4,opt,name=arch,proto3" json:"arch,omitempty"`
	UptimeSeconds    uint64                 `protobuf:"varint,5,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	CpuCount         int32                  `protobuf:"varint,6,opt,name=cpu_count,json=cpuCount,proto3" json:"cpu_count,omitempty"`
	TotalMemoryBytes uint64                 `protobuf:"varint,7,opt,name=total_memory_bytes,json=totalMemoryBytes,proto3" json:"total_memory_bytes,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SystemInfo) Reset() {
	*x = SystemInfo{}
	mi := &file_gravity_monitor_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SystemInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemInfo) ProtoMessage() {}

func (x *SystemInfo) ProtoReflect() protoreflect.Message {
	mi := &file_gravity_monitor_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemInfo.ProtoReflect.Descriptor instead.
func (*SystemInfo) Descriptor() ([]byte, []int) {
	return file_gravity_monitor_proto_rawDescGZIP(), []int{6}
}

func (x *SystemInfo) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *SystemInfo) GetKernelVersion() string {
	if x != nil {
		return x.KernelVersion
	}
	return ""
}

func (x *SystemInfo) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *SystemInfo) GetArch() string {
	if x != nil {
		return x.Arch
	}
	return ""
}

func (x *SystemInfo) GetUptimeSeconds() uint64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

func (x *SystemInfo) GetCpuCount() int32 {
	if x != nil {
		return x.CpuCount
	}
	return 0
}

func (x *SystemInfo) GetTotalMemoryBytes() uint64 {
	if x != nil {
		return x.TotalMemoryBytes
	}
	return 0
}

type ContainerMetrics struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	EntityId    string                 `protobuf:"bytes,1,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"` // deployment ID or sandbox ID — identifies what the container runs
	ContainerId string                 `protobuf:"bytes,2,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	Image       string                 `protobuf:"bytes,3,opt,name=image,proto3" json:"image,omitempty"`
	State       string                 `protobuf:"bytes,4,opt,name=state,proto3" json:"state,omitempty"`
	// CPU
	CpuUsagePercent     float64 `protobuf:"fixed64,5,opt,name=cpu_usage_percent,json=cpuUsagePercent,proto3" json:"cpu_usage_percent,omitempty"`
	CpuThrottledPeriods uint64  `protobuf:"varint,6,opt,name=cpu_throttled_periods,json=cpuThrottledPeriods,proto3" json:"cpu_throttled_periods,omitempty"`
	CpuTotalPeriods     uint64  `protobuf:"varint,7,opt,name=cpu_total_periods,json=cpuTotalPeriods,proto3" json:"cpu_total_periods,omitempty"`
	CpuLimitMillicores  int32   `protobuf:"varint,8,opt,name=cpu_limit_millicores,json=cpuLimitMillicores,proto3" json:"cpu_limit_millicores,omitempty"`
	// Memory
	MemoryUsageBytes uint64 `protobuf:"varint,9,opt,name=memory_usage_bytes,json=memoryUsageBytes,proto3" json:"memory_usage_bytes,omitempty"`
	MemoryLimitBytes uint64 `protobuf:"varint,10,opt,name=memory_limit_bytes,json=memoryLimitBytes,proto3" json:"memory_limit_bytes,omitempty"`
	MemoryRssBytes   uint64 `protobuf:"varint,11,opt,name=memory_rss_bytes,json=memoryRssBytes,proto3" json:"memory_rss_bytes,omitempty"`
	MemoryCacheBytes uint64 `protobuf:"varint,12,opt,name=memory_cache_bytes,json=memoryCacheBytes,proto3" json:"memory_cache_bytes,omitempty"`
	MemorySwapBytes  uint64 `protobuf:"varint,13,opt,name=memory_swap_bytes,json=memorySwapBytes,proto3" json:"memory_swap_bytes,omitempty"`
	OomKillCount     uint32 `protobuf:"varint,14,opt,name=oom_kill_count,json=oomKillCount,proto3" json:"oom_kill_count,omitempty"`
	// Network (deltas)
	NetRxBytesDelta   uint64 `protobuf:"varint,15,opt,name=net_rx_bytes_delta,json=netRxBytesDelta,proto3" json:"net_rx_bytes_delta,omitempty"`
	NetTxBytesDelta   uint64 `protobuf:"varint,16,opt,name=net_tx_bytes_delta,json=netTxBytesDelta,proto3" json:"net_tx_bytes_delta,omitempty"`
	NetRxPacketsDelta uint64 `protobuf:"varint,17,opt,name=net_rx_packets_delta,json=netRxPacketsDelta,proto3" json:"net_rx_packets_delta,omitempty"`
	NetTxPacketsDelta uint64 `protobuf:"varint,18,opt,name=net_tx_packets_delta,json=netTxPacketsDelta,proto3" json:"net_tx_packets_delta,omitempty"`
	// Block I/O (deltas)
	BlkioReadBytesDelta  uint64 `protobuf:"varint,19,opt,name=blkio_read_bytes_delta,json=blkioReadBytesDelta,proto3" json:"blkio_read_bytes_delta,omitempty"`
	BlkioWriteBytesDelta uint64 `protobuf:"varint,20,opt,name=blkio_write_bytes_delta,json=blkioWriteBytesDelta,proto3" json:"blkio_write_bytes_delta,omitempty"`
	// Process
	PidCount uint32 `protobuf:"varint,21,opt,name=pid_count,json=pidCount,proto3" json:"pid_count,omitempty"`
	// Health/Identity
	Healthy          bool   `protobuf:"varint,22,opt,name=healthy,proto3" json:"healthy,omitempty"`
	InflightRequests uint32 `protobuf:"varint,23,opt,name=inflight_requests,json=inflightRequests,proto3" json:"inflight_requests,omitempty"`
	StartedAtUs      int64  `protobuf:"varint,24,opt,name=started_at_us,json=startedAtUs,proto3" json:"started_at_us,omitempty"`
	LastUpdatedUs    int64  `protobuf:"varint,25,opt,name=last_updated_us,json=lastUpdatedUs,proto3" json:"last_updated_us,omitempty"`
	Ipv4Address      string `protobuf:"bytes,26,opt,name=ipv4_address,json=ipv4Address,proto3" json:"ipv4_address,omitempty"`
	Ipv6Address      string `protobuf:"bytes,27,opt,name=ipv6_address,json=ipv6Address,proto3" json:"ipv6_address,omitempty"`
	// Traffic / Request Stats
	UptimeSeconds      float64           `protobuf:"fixed64,28,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	TotalRequests      uint64            `protobuf:"varint,29,opt,name=total_requests,json=totalRequests,proto3" json:"total_requests,omitempty"`
	InProgressRequests uint32            `protobuf:"varint,30,opt,name=in_progress_requests,json=inProgressRequests,proto3" json:"in_progress_requests,omitempty"`
	StatusCodes        *StatusCodeCounts `protobuf:"bytes,31,opt,name=status_codes,json=statusCodes,proto3" json:"status_codes,omitempty"`
	Duration           *DurationStats    `protobuf:"bytes,32,opt,name=duration,proto3" json:"duration,omitempty"`
	TrafficBytes       *ByteStats        `protobuf:"bytes,33,opt,name=traffic_bytes,json=trafficBytes,proto3" json:"traffic_bytes,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ContainerMetrics) Reset() {
	*x = ContainerMetrics{}
	mi := &file_gravity_monitor_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContainerMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainerMetrics) ProtoMessage() {}

func (x *ContainerMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_gravity_monitor_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContainerMetrics.ProtoReflect.Descriptor instead.
func (*ContainerMetrics) Descriptor() ([]byte, []int) {
	return file_gravity_monitor_proto_rawDescGZIP(), []int{7}
}

func (x *ContainerMetrics) GetEntityId() string {
	if x != nil {
		return x.EntityId
	}
	return ""
}

func (x *ContainerMetrics) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

func (x *ContainerMetrics) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *ContainerMetrics) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *ContainerMetrics) GetCpuUsagePercent() float64 {
	if x != nil {
		return x.CpuUsagePercent
	}
	return 0
}

func (x *ContainerMetrics) GetCpuThrottledPeriods() uint64 {
	if x != nil {
		return x.CpuThrottledPeriods
	}
	return 0
}

func (x *ContainerMetrics) GetCpuTotalPeriods() uint64 {
	if x != nil {
		return x.CpuTotalPeriods
	}
	return 0
}

func (x *ContainerMetrics) GetCpuLimitMillicores() int32 {
	if x != nil {
		return x.CpuLimitMillicores
	}
	return 0
}

func (x *ContainerMetrics) GetMemoryUsageBytes() uint64 {
	if x != nil {
		return x.MemoryUsageBytes
	}
	return 0
}

func (x *ContainerMetrics) GetMemoryLimitBytes() uint64 {
	if x != nil {
		return x.MemoryLimitBytes
	}
	return 0
}

func (x *ContainerMetrics) GetMemoryRssBytes() uint64 {
	if x != nil {
		return x.MemoryRssBytes
	}
	return 0
}

func (x *ContainerMetrics) GetMemoryCacheBytes() uint64 {
	if x != nil {
		return x.MemoryCacheBytes
	}
	return 0
}

func (x *ContainerMetrics) GetMemorySwapBytes() uint64 {
	if x != nil {
		return x.MemorySwapBytes
	}
	return 0
}

func (x *ContainerMetrics) GetOomKillCount() uint32 {
	if x != nil {
		return x.OomKillCount
	}
	return 0
}

func (x *ContainerMetrics) GetNetRxBytesDelta() uint64 {
	if x != nil {
		return x.NetRxBytesDelta
	}
	return 0
}

func (x *ContainerMetrics) GetNetTxBytesDelta() uint64 {
	if x != nil {
		return x.NetTxBytesDelta
	}
	return 0
}

func (x *ContainerMetrics) GetNetRxPacketsDelta() uint64 {
	if x != nil {
		return x.NetRxPacketsDelta
	}
	return 0
}

func (x *ContainerMetrics) GetNetTxPacketsDelta() uint64 {
	if x != nil {
		return x.NetTxPacketsDelta
	}
	return 0
}

func (x *ContainerMetrics) GetBlkioReadBytesDelta() uint64 {
	if x != nil {
		return x.BlkioReadBytesDelta
	}
	return 0
}

func (x *ContainerMetrics) GetBlkioWriteBytesDelta() uint64 {
	if x != nil {
		return x.BlkioWriteBytesDelta
	}
	return 0
}

func (x *ContainerMetrics) GetPidCount() uint32 {
	if x != nil {
		return x.PidCount
	}
	return 0
}

func (x *ContainerMetrics) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *ContainerMetrics) GetInflightRequests() uint32 {
	if x != nil {
		return x.InflightRequests
	}
	return 0
}

func (x *ContainerMetrics) GetStartedAtUs() int64 {
	if x != nil {
		return x.StartedAtUs
	}
	return 0
}

func (x *ContainerMetrics) GetLastUpdatedUs() int64 {
	if x != nil {
		return x.LastUpdatedUs
	}
	return 0
}

func (x *ContainerMetrics) GetIpv4Address() string {
	if x != nil {
		return x.Ipv4Address
	}
	return ""
}

func (x *ContainerMetrics) GetIpv6Address() string {
	if x != nil {
		return x.Ipv6Address
	}
	return ""
}

func (x *ContainerMetrics) GetUptimeSeconds() float64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

func (x *ContainerMetrics) GetTotalRequests() uint64 {
	if x != nil {
		return x.TotalRequests
	}
	return 0
}

func (x *ContainerMetrics) GetInProgressRequests() uint32 {
	if x != nil {
		return x.InProgressRequests
	}
	return 0
}

func (x *ContainerMetrics) GetStatusCodes() *StatusCodeCounts {
	if x != nil {
		return x.StatusCodes
	}
	return nil
}

func (x *ContainerMetrics) GetDuration() *DurationStats {
	if x != nil {
		return x.Duration
	}
	return nil
}

func (x *ContainerMetrics) GetTrafficBytes() *ByteStats {
	if x != nil {
		return x.TrafficBytes
	}
	return nil
}

type StatusCodeCounts struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status_2Xx    uint64                 `protobuf:"varint,1,opt,name=status_2xx,json=status2xx,proto3" json:"status_2xx,omitempty"`
	Status_4Xx    uint64                 `protobuf:"varint,2,opt,name=status_4xx,json=status4xx,proto3" json:"status_4xx,omitempty"`
	Status_5Xx    uint64                 `protobuf:"varint,3,opt,name=status_5xx,json=status5xx,proto3" json:"status_5xx,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusCodeCounts) Reset() {
	*x = StatusCodeCounts{}
	mi := &file_gravity_monitor_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusCodeCounts) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusCodeCounts) ProtoMessage() {}

func (x *StatusCodeCounts) ProtoReflect() protoreflect.Message {
	mi := &file_gravity_monitor_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusCodeCounts.ProtoReflect.Descriptor instead.
func (*StatusCodeCounts) Descriptor() ([]byte, []int) {
	return file_gravity_monitor_proto_rawDescGZIP(), []int{8}
}

func (x *StatusCodeCounts) GetStatus_2Xx() uint64 {
	if x != nil {
		return x.Status_2Xx
	}
	return 0
}

func (x *StatusCodeCounts) GetStatus_4Xx() uint64 {
	if x != nil {
		return x.Status_4Xx
	}
	return 0
}

func (x *StatusCodeCounts) GetStatus_5Xx() uint64 {
	if x != nil {
		return x.Status_5Xx
	}
	return 0
}

type DurationStats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AvgMs         float64                `protobuf:"fixed64,1,opt,name=avg_ms,json=avgMs,proto3" json:"avg_ms,omitempty"`
	MaxMs         float64                `protobuf:"fixed64,2,opt,name=max_ms,json=maxMs,proto3" json:"max_ms,omitempty"`
	P50Ms         float64                `protobuf:"fixed64,3,opt,name=p50_ms,json=p50Ms,proto3" json:"p50_ms,omitempty"`
	P95Ms         float64                `protobuf:"fixed64,4,opt,name=p95_ms,json=p95Ms,proto3" json:"p95_ms,omitempty"`
	P99Ms         float64                `protobuf:"fixed64,5,opt,name=p99_ms,json=p99Ms,proto3" json:"p99_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DurationStats) Reset() {
	*x = DurationStats{}
	mi := &file_gravity_monitor_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DurationStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DurationStats) ProtoMessage() {}

func (x *DurationStats) ProtoReflect() protoreflect.Message {
	mi := &file_gravity_monitor_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DurationStats.ProtoReflect.Descriptor instead.
func (*DurationStats) Descriptor() ([]byte, []int) {
	return file_gravity_monitor_proto_rawDescGZIP(), []int{9}
}

func (x *DurationStats) GetAvgMs() float64 {
	if x != nil {
		return x.AvgMs
	}
	return 0
}

func (x *DurationStats) GetMaxMs() float64 {
	if x != nil {
		return x.MaxMs
	}
	return 0
}

func (x *DurationStats) GetP50Ms() float64 {
	if x != nil {
		return x.P50Ms
	}
	return 0
}

func (x *DurationStats) GetP95Ms() float64 {
	if x != nil {
		return x.P95Ms
	}
	return 0
}

func (x *DurationStats) GetP99Ms() float64 {
	if x != nil {
		return x.P99Ms
	}
	return 0
}

type ByteStats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InBytes       uint64                 `protobuf:"varint,1,opt,name=in_bytes,json=inBytes,proto3" json:"in_bytes,omitempty"`
	OutBytes      uint64                 `protobuf:"varint,2,opt,name=out_bytes,json=outBytes,proto3" json:"out_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ByteStats) Reset() {
	*x = ByteStats{}
	mi := &file_gravity_monitor_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ByteStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ByteStats) ProtoMessage() {}

func (x *ByteStats) ProtoReflect() protoreflect.Message {
	mi := &file_gravity_monitor_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ByteStats.ProtoReflect.Descriptor instead.
func (*ByteStats) Descriptor() ([]byte, []int) {
	return file_gravity_monitor_proto_rawDescGZIP(), []int{10}
}

func (x *ByteStats) GetInBytes() uint64 {
	if x != nil {
		return x.InBytes
	}
	return 0
}

func (x *ByteStats) GetOutBytes() uint64 {
	if x != nil {
		return x.OutBytes
	}
	return 0
}

type CapacitySummary struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	CpuPressure       float64                `protobuf:"fixed64,1,opt,name=cpu_pressure,json=cpuPressure,proto3" json:"cpu_pressure,omitempty"`
	MemoryPressure    float64                `protobuf:"fixed64,2,opt,name=memory_pressure,json=memoryPressure,proto3" json:"memory_pressure,omitempty"`
	DiskPressure      float64                `protobuf:"fixed64,3,opt,name=disk_pressure,json=diskPressure,proto3" json:"disk_pressure,omitempty"`
	NetworkPressure   float64                `protobuf:"fixed64,4,opt,name=network_pressure,json=networkPressure,proto3" json:"network_pressure,omitempty"`
	CompositeScore    float64                `protobuf:"fixed64,5,opt,name=composite_score,json=compositeScore,proto3" json:"composite_score,omitempty"`
	TotalContainers   int32                  `protobuf:"varint,6,opt,name=total_containers,json=totalContainers,proto3" json:"total_containers,omitempty"`
	RunningContainers int32                  `protobuf:"varint,7,opt,name=running_containers,json=runningContainers,proto3" json:"running_containers,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CapacitySummary) Reset() {
	*x = CapacitySummary{}
	mi := &file_gravity_monitor_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CapacitySummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CapacitySummary) ProtoMessage() {}

func (x *CapacitySummary) ProtoReflect() protoreflect.Message {
	mi := &file_gravity_monitor_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CapacitySummary.ProtoReflect.Descriptor instead.
func (*CapacitySummary) Descriptor() ([]byte, []int) {
	return file_gravity_monitor_proto_rawDescGZIP(), []int{11}
}

func (x *CapacitySummary) GetCpuPressure() float64 {
	if x != nil {
		return x.CpuPressure
	}
	return 0
}

func (x *CapacitySummary) GetMemoryPressure() float64 {
	if x != nil {
		return x.MemoryPressure
	}
	return 0
}

func (x *CapacitySummary) GetDiskPressure() float64 {
	if x != nil {
		return x.DiskPressure
	}
	return 0
}

func (x *CapacitySummary) GetNetworkPressure() float64 {
	if x != nil {
		return x.NetworkPressure
	}
	return 0
}

func (x *CapacitySummary) GetCompositeScore() float64 {
	if x != nil {
		return x.CompositeScore
	}
	return 0
}

func (x *CapacitySummary) GetTotalContainers() int32 {
	if x != nil {
		return x.TotalContainers
	}
	return 0
}

func (x *CapacitySummary) GetRunningContainers() int32 {
	if x != nil {
		return x.RunningContainers
	}
	return 0
}

type NodeEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TimestampUs   int64                  `protobuf:"varint,1,opt,name=timestamp_us,json=timestampUs,proto3" json:"timestamp_us,omitempty"`
	Level         NodeEventLevel         `protobuf:"varint,2,opt,name=level,proto3,enum=gravity.NodeEventLevel" json:"level,omitempty"`
	Type          NodeEventType          `protobuf:"varint,3,opt,name=type,proto3,enum=gravity.NodeEventType" json:"type,omitempty"`
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,5,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeEvent) Reset() {
	*x = NodeEvent{}
	mi := &file_gravity_monitor_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeEvent) ProtoMessage() {}

func (x *NodeEvent) ProtoReflect() protoreflect.Message {
	mi := &file_gravity_monitor_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeEvent.ProtoReflect.Descriptor instead.
func (*NodeEvent) Descriptor() ([]byte, []int) {
	return file_gravity_monitor_proto_rawDescGZIP(), []int{12}
}

func (x *NodeEvent) GetTimestampUs() int64 {
	if x != nil {
		return x.TimestampUs
	}
	return 0
}

func (x *NodeEvent) GetLevel() NodeEventLevel {
	if x != nil {
		return x.Level
	}
	return NodeEventLevel_NODE_EVENT_LEVEL_UNSPECIFIED
}

func (x *NodeEvent) GetType() NodeEventType {
	if x != nil {
		return x.Type
	}
	return NodeEventType_NODE_EVENT_TYPE_UNSPECIFIED
}

func (x *NodeEvent) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *NodeEvent) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type MonitorCommand struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Command:
	//
	//	*MonitorCommand_AdjustInterval
	//	*MonitorCommand_RequestSnapshot
	Command       isMonitorCommand_Command `protobuf_oneof:"command"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MonitorCommand) Reset() {
	*x = MonitorCommand{}
	mi := &file_gravity_monitor_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MonitorCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MonitorCommand) ProtoMessage() {}

func (x *MonitorCommand) ProtoReflect() protoreflect.Message {
	mi := &file_gravity_monitor_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MonitorCommand.ProtoReflect.Descriptor instead.
func (*MonitorCommand) Descriptor() ([]byte, []int) {
	return file_gravity_monitor_proto_rawDescGZIP(), []int{13}
}

func (x *MonitorCommand) GetCommand() isMonitorCommand_Command {
	if x != nil {
		return x.Command
	}
	return nil
}

func (x *MonitorCommand) GetAdjustInterval() *AdjustMonitorInterval {
	if x != nil {
		if x, ok := x.Command.(*MonitorCommand_AdjustInterval); ok {
			return x.AdjustInterval
		}
	}
	return nil
}

func (x *MonitorCommand) GetRequestSnapshot() *RequestMonitorSnapshot {
	if x != nil {
		if x, ok := x.Command.(*MonitorCommand_RequestSnapshot); ok {
			return x.RequestSnapshot
		}
	}
	return nil
}

type isMonitorCommand_Command interface {
	isMonitorCommand_Command()
}

type MonitorCommand_AdjustInterval struct {
	AdjustInterval *AdjustMonitorInterval `protobuf:"bytes,1,opt,name=adjust_interval,json=adjustInterval,proto3,oneof"`
}

type MonitorCommand_RequestSnapshot struct {
	RequestSnapshot *RequestMonitorSnapshot `protobuf:"bytes,2,opt,name=request_snapshot,json=requestSnapshot,proto3,oneof"`
}

func (*MonitorCommand_AdjustInterval) isMonitorCommand_Command() {}

func (*MonitorCommand_RequestSnapshot) isMonitorCommand_Command() {}

type AdjustMonitorInterval struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	IntervalSeconds int32                  `protobuf:"varint,1,opt,name=interval_seconds,json=intervalSeconds,proto3" json:"interval_seconds,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AdjustMonitorInterval) Reset() {
	*x = AdjustMonitorInterval{}
	mi := &file_gravity_monitor_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdjustMonitorInterval) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdjustMonitorInterval) ProtoMessage() {}

func (x *AdjustMonitorInterval) ProtoReflect() protoreflect.Message {
	mi := &file_gravity_monitor_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdjustMonitorInterval.ProtoReflect.Descriptor instead.
func (*AdjustMonitorInterval) Descriptor() ([]byte, []int) {
	return file_gravity_monitor_proto_rawDescGZIP(), []int{14}
}

func (x *AdjustMonitorInterval) GetIntervalSeconds() int32 {
	if x != nil {
		return x.IntervalSeconds
	}
	return 0
}

type RequestMonitorSnapshot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestMonitorSnapshot) Reset() {
	*x = RequestMonitorSnapshot{}
	mi := &file_gravity_monitor_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestMonitorSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestMonitorSnapshot) ProtoMessage() {}

func (x *RequestMonitorSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_gravity_monitor_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestMonitorSnapshot.ProtoReflect.Descriptor instead.
func (*RequestMonitorSnapshot) Descriptor() ([]byte, []int) {
	return file_gravity_monitor_proto_rawDescGZIP(), []int{15}
}

var File_gravity_monitor_proto protoreflect.FileDescriptor

const file_gravity_monitor_proto_rawDesc = "" +
	"\n" +
	"\x15gravity_monitor.proto\x12\agravity\"\xe9\x02\n" +
	"\x11NodeMonitorReport\x12\x1d\n" +
	"\n" +
	"machine_id\x18\x01 \x01(\tR\tmachineId\x12$\n" +
	"\x0ereported_at_us\x18\x02 \x01(\x03R\freportedAtUs\x12\x10\n" +
	"\x03seq\x18\x03 \x01(\x04R\x03seq\x12(\n" +
	"\x04host\x18\x04 \x01(\v2\x14.gravity.HostMetricsR\x04host\x129\n" +
	"\n" +
	"containers\x18\x05 \x03(\v2\x19.gravity.ContainerMetricsR\n" +
	"containers\x124\n" +
	"\bcapacity\x18\x06 \x01(\v2\x18.gravity.CapacitySummaryR\bcapacity\x12*\n" +
	"\x06events\x18\a \x03(\v2\x12.gravity.NodeEventR\x06events\x126\n" +
	"\x17report_interval_seconds\x18\b \x01(\x05R\x15reportIntervalSeconds\"\x8e\x02\n" +
	"\vHostMetrics\x12%\n" +
	"\x03cpu\x18\x01 \x01(\v2\x13.gravity.CpuMetricsR\x03cpu\x12.\n" +
	"\x06memory\x18\x02 \x01(\v2\x16.gravity.MemoryMetricsR\x06memory\x12*\n" +
	"\x05disks\x18\x03 \x03(\v2\x14.gravity.DiskMetricsR\x05disks\x12O\n" +
	"\x12network_interfaces\x18\x04 \x03(\v2 .gravity.NetworkInterfaceMetricsR\x11networkInterfaces\x12+\n" +
	"\x06system\x18\x05 \x01(\v2\x13.gravity.SystemInfoR\x06system\"\xda\x01\n" +
	"\n" +
	"CpuMetrics\x12#\n" +
	"\rusage_percent\x18\x01 \x01(\x01R\fusagePercent\x12,\n" +
	"\x12core_usage_percent\x18\x02 \x03(\x01R\x10coreUsagePercent\x12\x1c\n" +
	"\n" +
	"load_avg_1\x18\x03 \x01(\x01R\bloadAvg1\x12\x1c\n" +
	"\n" +
	"load_avg_5\x18\x04 \x01(\x01R\bloadAvg5\x12\x1e\n" +
	"\vload_avg_15\x18\x05 \x01(\x01R\tloadAvg15\x12\x1d\n" +
	"\n" +
	"core_count\x18\x06 \x01(\x05R\tcoreCount\"\xb7\x02\n" +
	"\rMemoryMetrics\x12\x1f\n" +
	"\vtotal_bytes\x18\x01 \x01(\x04R\n" +
	"totalBytes\x12\x1d\n" +
	"\n" +
	"used_bytes\x18\x02 \x01(\x04R\tusedBytes\x12'\n" +
	"\x0favailable_bytes\x18\x03 \x01(\x04R\x0eavailableBytes\x12!\n" +
	"\fcached_bytes\x18\x04 \x01(\x04R\vcachedBytes\x12#\n" +
	"\rbuffers_bytes\x18\x05 \x01(\x04R\fbuffersBytes\x12(\n" +
	"\x10swap_total_bytes\x18\x06 \x01(\x04R\x0eswapTotalBytes\x12&\n" +
	"\x0fswap_used_bytes\x18\a \x01(\x04R\rswapUsedBytes\x12#\n" +
	"\rusage_percent\x18\b \x01(\x01R\fusagePercent\"\xd5\x03\n" +
	"\vDiskMetrics\x12\x1f\n" +
	"\vmount_point\x18\x01 \x01(\tR\n" +
	"mountPoint\x12\x16\n" +
	"\x06device\x18\x02 \x01(\tR\x06device\x12\x17\n" +
	"\afs_type\x18\x03 \x01(\tR\x06fsType\x12\x1f\n" +
	"\vtotal_bytes\x18\x04 \x01(\x04R\n" +
	"totalBytes\x12\x1d\n" +
	"\n" +
	"used_bytes\x18\x05 \x01(\x04R\tusedBytes\x12'\n" +
	"\x0favailable_bytes\x18\x06 \x01(\x04R\x0eavailableBytes\x12#\n" +
	"\rusage_percent\x18\a \x01(\x01R\fusagePercent\x12!\n" +
	"\finodes_total\x18\b \x01(\x04R\vinodesTotal\x12\x1f\n" +
	"\vinodes_used\x18\t \x01(\x04R\n" +
	"inodesUsed\x12(\n" +
	"\x10read_bytes_delta\x18\n" +
	" \x01(\x04R\x0ereadBytesDelta\x12*\n" +
	"\x11write_bytes_delta\x18\v \x01(\x04R\x0fwriteBytesDelta\x12$\n" +
	"\x0eread_ops_delta\x18\f \x01(\x04R\freadOpsDelta\x12&\n" +
	"\x0fwrite_ops_delta\x18\r \x01(\x04R\rwriteOpsDelta\"\xa7\x03\n" +
	"\x17NetworkInterfaceMetrics\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12$\n" +
	"\x0erx_bytes_delta\x18\x02 \x01(\x04R\frxBytesDelta\x12$\n" +
	"\x0etx_bytes_delta\x18\x03 \x01(\x04R\ftxBytesDelta\x12(\n" +
	"\x10rx_packets_delta\x18\x04 \x01(\x04R\x0erxPacketsDelta\x12(\n" +
	"\x10tx_packets_delta\x18\x05 \x01(\x04R\x0etxPacketsDelta\x12&\n" +
	"\x0frx_errors_delta\x18\x06 \x01(\x04R\rrxErrorsDelta\x12&\n" +
	"\x0ftx_errors_delta\x18\a \x01(\x04R\rtxErrorsDelta\x12$\n" +
	"\x0erx_drops_delta\x18\b \x01(\x04R\frxDropsDelta\x12$\n" +
	"\x0etx_drops_delta\x18\t \x01(\x04R\ftxDropsDelta\x12\x1d\n" +
	"\n" +
	"link_state\x18\n" +
	" \x01(\tR\tlinkState\x12\x1d\n" +
	"\n" +
	"speed_mbps\x18\v \x01(\x04R\tspeedMbps\"\xe5\x01\n" +
	"\n" +
	"SystemInfo\x12\x1a\n" +
	"\bhostname\x18\x01 \x01(\tR\bhostname\x12%\n" +
	"\x0ekernel_version\x18\x02 \x01(\tR\rkernelVersion\x12\x0e\n" +
	"\x02os\x18\x03 \x01(\tR\x02os\x12\x12\n" +
	"\x04arch\x18\x04 \x01(\tR\x04arch\x12%\n" +
	"\x0euptime_seconds\x18\x05 \x01(\x04R\ruptimeSeconds\x12\x1b\n" +
	"\tcpu_count\x18\x06 \x01(\x05R\bcpuCount\x12,\n" +
	"\x12total_memory_bytes\x18\a \x01(\x04R\x10totalMemoryBytes\"\x8b\v\n" +
	"\x10ContainerMetrics\x12\x1b\n" +
	"\tentity_id\x18\x01 \x01(\tR\bentityId\x12!\n" +
	"\fcontainer_id\x18\x02 \x01(\tR\vcontainerId\x12\x14\n" +
	"\x05image\x18\x03 \x01(\tR\x05image\x12\x14\n" +
	"\x05state\x18\x04 \x01(\tR\x05state\x12*\n" +
	"\x11cpu_usage_percent\x18\x05 \x01(\x01R\x0fcpuUsagePercent\x122\n" +
	"\x15cpu_throttled_periods\x18\x06 \x01(\x04R\x13cpuThrottledPeriods\x12*\n" +
	"\x11cpu_total_periods\x18\a \x01(\x04R\x0fcpuTotalPeriods\x120\n" +
	"\x14cpu_limit_millicores\x18\b \x01(\x05R\x12cpuLimitMillicores\x12,\n" +
	"\x12memory_usage_bytes\x18\t \x01(\x04R\x10memoryUsageBytes\x12,\n" +
	"\x12memory_limit_bytes\x18\n" +
	" \x01(\x04R\x10memoryLimitBytes\x12(\n" +
	"\x10memory_rss_bytes\x18\v \x01(\x04R\x0ememoryRssBytes\x12,\n" +
	"\x12memory_cache_bytes\x18\f \x01(\x04R\x10memoryCacheBytes\x12*\n" +
	"\x11memory_swap_bytes\x18\r \x01(\x04R\x0fmemorySwapBytes\x12$\n" +
	"\x0eoom_kill_count\x18\x0e \x01(\rR\foomKillCount\x12+\n" +
	"\x12net_rx_bytes_delta\x18\x0f \x01(\x04R\x0fnetRxBytesDelta\x12+\n" +
	"\x12net_tx_bytes_delta\x18\x10 \x01(\x04R\x0fnetTxBytesDelta\x12/\n" +
	"\x14net_rx_packets_delta\x18\x11 \x01(\x04R\x11netRxPacketsDelta\x12/\n" +
	"\x14net_tx_packets_delta\x18\x12 \x01(\x04R\x11netTxPacketsDelta\x123\n" +
	"\x16blkio_read_bytes_delta\x18\x13 \x01(\x04R\x13blkioReadBytesDelta\x125\n" +
	"\x17blkio_write_bytes_delta\x18\x14 \x01(\x04R\x14blkioWriteBytesDelta\x12\x1b\n" +
	"\tpid_count\x18\x15 \x01(\rR\bpidCount\x12\x18\n" +
	"\ahealthy\x18\x16 \x01(\bR\ahealthy\x12+\n" +
	"\x11inflight_requests\x18\x17 \x01(\rR\x10inflightRequests\x12\"\n" +
	"\rstarted_at_us\x18\x18 \x01(\x03R\vstartedAtUs\x12&\n" +
	"\x0flast_updated_us\x18\x19 \x01(\x03R\rlastUpdatedUs\x12!\n" +
	"\fipv4_address\x18\x1a \x01(\tR\vipv4Address\x12!\n" +
	"\fipv6_address\x18\x1b \x01(\tR\vipv6Address\x12%\n" +
	"\x0euptime_seconds\x18\x1c \x01(\x01R\ruptimeSeconds\x12%\n" +
	"\x0etotal_requests\x18\x1d \x01(\x04R\rtotalRequests\x120\n" +
	"\x14in_progress_requests\x18\x1e \x01(\rR\x12inProgressRequests\x12<\n" +
	"\fstatus_codes\x18\x1f \x01(\v2\x19.gravity.StatusCodeCountsR\vstatusCodes\x122\n" +
	"\bduration\x18  \x01(\v2\x16.gravity.DurationStatsR\bduration\x127\n" +
	"\rtraffic_bytes\x18! \x01(\v2\x12.gravity.ByteStatsR\ftrafficBytes\"o\n" +
	"\x10StatusCodeCounts\x12\x1d\n" +
	"\n" +
	"status_2xx\x18\x01 \x01(\x04R\tstatus2xx\x12\x1d\n" +
	"\n" +
	"status_4xx\x18\x02 \x01(\x04R\tstatus4xx\x12\x1d\n" +
	"\n" +
	"status_5xx\x18\x03 \x01(\x04R\tstatus5xx\"\x82\x01\n" +
	"\rDurationStats\x12\x15\n" +
	"\x06avg_ms\x18\x01 \x01(\x01R\x05avgMs\x12\x15\n" +
	"\x06max_ms\x18\x02 \x01(\x01R\x05maxMs\x12\x15\n" +
	"\x06p50_ms\x18\x03 \x01(\x01R\x05p50Ms\x12\x15\n" +
	"\x06p95_ms\x18\x04 \x01(\x01R\x05p95Ms\x12\x15\n" +
	"\x06p99_ms\x18\x05 \x01(\x01R\x05p99Ms\"C\n" +
	"\tByteStats\x12\x19\n" +
	"\bin_bytes\x18\x01 \x01(\x04R\ainBytes\x12\x1b\n" +
	"\tout_bytes\x18\x02 \x01(\x04R\boutBytes\"\xb0\x02\n" +
	"\x0fCapacitySummary\x12!\n" +
	"\fcpu_pressure\x18\x01 \x01(\x01R\vcpuPressure\x12'\n" +
	"\x0fmemory_pressure\x18\x02 \x01(\x01R\x0ememoryPressure\x12#\n" +
	"\rdisk_pressure\x18\x03 \x01(\x01R\fdiskPressure\x12)\n" +
	"\x10network_pressure\x18\x04 \x01(\x01R\x0fnetworkPressure\x12'\n" +
	"\x0fcomposite_score\x18\x05 \x01(\x01R\x0ecompositeScore\x12)\n" +
	"\x10total_containers\x18\x06 \x01(\x05R\x0ftotalContainers\x12-\n" +
	"\x12running_containers\x18\a \x01(\x05R\x11runningContainers\"\x9e\x02\n" +
	"\tNodeEvent\x12!\n" +
	"\ftimestamp_us\x18\x01 \x01(\x03R\vtimestampUs\x12-\n" +
	"\x05level\x18\x02 \x01(\x0e2\x17.gravity.NodeEventLevelR\x05level\x12*\n" +
	"\x04type\x18\x03 \x01(\x0e2\x16.gravity.NodeEventTypeR\x04type\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\x12<\n" +
	"\bmetadata\x18\x05 \x03(\v2 .gravity.NodeEvent.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xb4\x01\n" +
	"\x0eMonitorCommand\x12I\n" +
	"\x0fadjust_interval\x18\x01 \x01(\v2\x1e.gravity.AdjustMonitorIntervalH\x00R\x0eadjustInterval\x12L\n" +
	"\x10request_snapshot\x18\x02 \x01(\v2\x1f.gravity.RequestMonitorSnapshotH\x00R\x0frequestSnapshotB\t\n" +
	"\acommand\"B\n" +
	"\x15AdjustMonitorInterval\x12)\n" +
	"\x10interval_seconds\x18\x01 \x01(\x05R\x0fintervalSeconds\"\x18\n" +
	"\x16RequestMonitorSnapshot*\xa3\x01\n" +
	"\x0eNodeEventLevel\x12 \n" +
	"\x1cNODE_EVENT_LEVEL_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15NODE_EVENT_LEVEL_INFO\x10\x01\x12\x19\n" +
	"\x15NODE_EVENT_LEVEL_WARN\x10\x02\x12\x1a\n" +
	"\x16NODE_EVENT_LEVEL_ERROR\x10\x03\x12\x1d\n" +
	"\x19NODE_EVENT_LEVEL_CRITICAL\x10\x04*\x82\x03\n" +
	"\rNodeEventType\x12\x1f\n" +
	"\x1bNODE_EVENT_TYPE_UNSPECIFIED\x10\x00\x12#\n" +
	"\x1fNODE_EVENT_TYPE_CONTAINER_START\x10\x01\x12\"\n" +
	"\x1eNODE_EVENT_TYPE_CONTAINER_STOP\x10\x02\x12!\n" +
	"\x1dNODE_EVENT_TYPE_CONTAINER_OOM\x10\x03\x12+\n" +
	"'NODE_EVENT_TYPE_CONTAINER_HEALTH_CHANGE\x10\x04\x12&\n" +
	"\"NODE_EVENT_TYPE_PRESSURE_THRESHOLD\x10\x05\x12$\n" +
	" NODE_EVENT_TYPE_DISK_NEARLY_FULL\x10\x06\x12#\n" +
	"\x1fNODE_EVENT_TYPE_COLLECTOR_ERROR\x10\a\x12\"\n" +
	"\x1eNODE_EVENT_TYPE_PRESSURE_ALERT\x10\b\x12 \n" +
	"\x1cNODE_EVENT_TYPE_HEALTH_ALERT\x10\tB.Z,github.com/agentuity/go-common/gravity/protob\x06proto3"

var (
	file_gravity_monitor_proto_rawDescOnce sync.Once
	file_gravity_monitor_proto_rawDescData []byte
)

func file_gravity_monitor_proto_rawDescGZIP() []byte {
	file_gravity_monitor_proto_rawDescOnce.Do(func() {
		file_gravity_monitor_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_gravity_monitor_proto_rawDesc), len(file_gravity_monitor_proto_rawDesc)))
	})
	return file_gravity_monitor_proto_rawDescData
}

var file_gravity_monitor_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_gravity_monitor_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_gravity_monitor_proto_goTypes = []any{
	(NodeEventLevel)(0),             // 0: gravity.NodeEventLevel
	(NodeEventType)(0),              // 1: gravity.NodeEventType
	(*NodeMonitorReport)(nil),       // 2: gravity.NodeMonitorReport
	(*HostMetrics)(nil),             // 3: gravity.HostMetrics
	(*CpuMetrics)(nil),              // 4: gravity.CpuMetrics
	(*MemoryMetrics)(nil),           // 5: gravity.MemoryMetrics
	(*DiskMetrics)(nil),             // 6: gravity.DiskMetrics
	(*NetworkInterfaceMetrics)(nil), // 7: gravity.NetworkInterfaceMetrics
	(*SystemInfo)(nil),              // 8: gravity.SystemInfo
	(*ContainerMetrics)(nil),        // 9: gravity.ContainerMetrics
	(*StatusCodeCounts)(nil),        // 10: gravity.StatusCodeCounts
	(*DurationStats)(nil),           // 11: gravity.DurationStats
	(*ByteStats)(nil),               // 12: gravity.ByteStats
	(*CapacitySummary)(nil),         // 13: gravity.CapacitySummary
	(*NodeEvent)(nil),               // 14: gravity.NodeEvent
	(*MonitorCommand)(nil),          // 15: gravity.MonitorCommand
	(*AdjustMonitorInterval)(nil),   // 16: gravity.AdjustMonitorInterval
	(*RequestMonitorSnapshot)(nil),  // 17: gravity.RequestMonitorSnapshot
	nil,                             // 18: gravity.NodeEvent.MetadataEntry
}
var file_gravity_monitor_proto_depIdxs = []int32{
	3,  // 0: gravity.NodeMonitorReport.host:type_name -> gravity.HostMetrics
	9,  // 1: gravity.NodeMonitorReport.containers:type_name -> gravity.ContainerMetrics
	13, // 2: gravity.NodeMonitorReport.capacity:type_name -> gravity.CapacitySummary
	14, // 3: gravity.NodeMonitorReport.events:type_name -> gravity.NodeEvent
	4,  // 4: gravity.HostMetrics.cpu:type_name -> gravity.CpuMetrics
	5,  // 5: gravity.HostMetrics.memory:type_name -> gravity.MemoryMetrics
	6,  // 6: gravity.HostMetrics.disks:type_name -> gravity.DiskMetrics
	7,  // 7: gravity.HostMetrics.network_interfaces:type_name -> gravity.NetworkInterfaceMetrics
	8,  // 8: gravity.HostMetrics.system:type_name -> gravity.SystemInfo
	10, // 9: gravity.ContainerMetrics.status_codes:type_name -> gravity.StatusCodeCounts
	11, // 10: gravity.ContainerMetrics.duration:type_name -> gravity.DurationStats
	12, // 11: gravity.ContainerMetrics.traffic_bytes:type_name -> gravity.ByteStats
	0,  // 12: gravity.NodeEvent.level:type_name -> gravity.NodeEventLevel
	1,  // 13: gravity.NodeEvent.type:type_name -> gravity.NodeEventType
	18, // 14: gravity.NodeEvent.metadata:type_name -> gravity.NodeEvent.MetadataEntry
	16, // 15: gravity.MonitorCommand.adjust_interval:type_name -> gravity.AdjustMonitorInterval
	17, // 16: gravity.MonitorCommand.request_snapshot:type_name -> gravity.RequestMonitorSnapshot
	17, // [17:17] is the sub-list for method output_type
	17, // [17:17] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_gravity_monitor_proto_init() }
func file_gravity_monitor_proto_init() {
	if File_gravity_monitor_proto != nil {
		return
	}
	file_gravity_monitor_proto_msgTypes[13].OneofWrappers = []any{
		(*MonitorCommand_AdjustInterval)(nil),
		(*MonitorCommand_RequestSnapshot)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gravity_monitor_proto_rawDesc), len(file_gravity_monitor_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_gravity_monitor_proto_goTypes,
		DependencyIndexes: file_gravity_monitor_proto_depIdxs,
		EnumInfos:         file_gravity_monitor_proto_enumTypes,
		MessageInfos:      file_gravity_monitor_proto_msgTypes,
	}.Build()
	File_gravity_monitor_proto = out.File
	file_gravity_monitor_proto_goTypes = nil
	file_gravity_monitor_proto_depIdxs = nil
}
