version: 2
pro: true

before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy

builds:
  - skip: true

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
