version: 2
pro: true

before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
