package dns

import (
	"fmt"
	"os"
)

// DefaultResolveConfFilename is the default filename for the resolv.conf file.
var DefaultResolveConfFilename = "/etc/resolv.conf"

// WriteResolvConf writes a resolv.conf file that points to a local DNS server
// with the default internal domain as the search domain.
// If filename is empty, it defaults to /etc/resolv.conf
func WriteResolvConf(filename string) error {
	if filename == "" {
		filename = DefaultResolveConfFilename
	}

	content := fmt.Sprintf(`# Generated by agentuity/go-common/dns
nameserver 127.0.0.1
search %s
`, DefaultInternalDomain)

	// Write the file with appropriate permissions (0644)
	if err := os.WriteFile(filename, []byte(content), 0644); err != nil {
		return fmt.Errorf("failed to write %s: %w", filename, err)
	}

	return nil
}
