name: Go

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

env:
  GOFIPS140: v1.0.0

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "stable"
      - name: Check vulnerabilities
        run: |
          go install golang.org/x/vuln/cmd/govulncheck@latest
          govulncheck ./...
      - name: Build
        run: go build -v ./...
      - name: Test
        run: go test -v -race ./...
      - name: Fuzz Testing
        run: |
          go test -fuzz=FuzzEncryptDecrypt ./crypto -fuzztime=3s
          go test -fuzz=FuzzDecryptMalformed ./crypto -fuzztime=3s
          go test -fuzz=FuzzCorruptionPositions ./crypto -fuzztime=3s
          go test -fuzz=FuzzPEMEncoding ./crypto -fuzztime=3s
          go test -fuzz=FuzzStreamingPatterns ./crypto -fuzztime=3s
          go test -fuzz=FuzzPartialCorruption ./crypto -fuzztime=3s
          go test -fuzz=FuzzDifferentKeyPairs ./crypto -fuzztime=3s
